### ISSUE TITLE
non-default port numbers when using :SSH service option and noVisualHostKey error

### ISSUE THREAD

**Issue by KLuka** [shellinabox/shellinabox#107]
_From [ele...@gmail.com](https://code.google.com/u/100101035320051471606/) on January 03, 2011 02:40:53_

i like the 'SSH' service option for shellinaboxd, but i ran into two problems when trying to use it

1. need to use non default port number 
since the -s option supports SSH:server, i extended this on my local copy to support SSH:server:port (port being optional). this will cause the ssh service to run with a -p flag. otherwise, port 22 is used as normal.

2. noVisualHostKey is not supported
on multiple boxes i tested, the noVisualHostKey was not recognized and threw out errors when trying to use the SSH service. i had to comment this flag out in order to get it to work with any of the servers i shell into

all the changes i've made to support the above two issues are in service.c, i have it attached below if you think this would be helpful to others.

**Attachment:** [service.c](http://code.google.com/p/shellinabox/issues/detail?id=107)

_Original issue: http://code.google.com/p/shellinabox/issues/detail?id=107_

**Comment by KLuka** [comment]
_From [ascot...@gmail.com](https://code.google.com/u/107950664407502898789/) on April 11, 2011 15:18:07_

This is exactly what I was looking for. I've tested this and this suggested change works as advertised. Please consider adding this as a feature.

**Comment by KLuka** [comment]
_From [beewoo...@gmail.com](https://code.google.com/u/107611011494747666553/) on March 31, 2012 15:19:32_

Please provide a patch intead of individual files.

BTW, the noVisualHostKey change has been made for 2.11.

**Status:** Accepted

**Comment by howtophil** [comment]
Was this never merged? My BBS runs on an alternate SSH port and shellinabox is useless without a way to change the port
