### ISSUE TITLE
Can't log in

### ISSUE THREAD

**Issue by KLuka** [shellinabox/shellinabox#113]
_From [dramp...@gmail.com](https://code.google.com/u/105605484611746698462/) on February 11, 2011 02:59:03_

May be something silly I am doing wrong: What steps will reproduce the problem? 1. Logging in What is the expected output? What do you see instead? I expect to be logged in but it says login incorrect What version of the product are you using? On what operating system? Version 2.10 CentOS Please provide any additional information below. When it says "Login:" on the webpage I enter root then my password but it says login incorrect when I have it right. Do I have to do root@hostname or something else? I have tried root@host already

_Original issue: http://code.google.com/p/shellinabox/issues/detail?id=113_

**Comment by KLuka** [comment]
_From [jmcdo...@gmail.com](https://code.google.com/u/112378838953435388147/) on March 04, 2011 03:13:19_

I'll ask the silly question...

Root login only works for ttys that are declared in the /etc/securetty file. Check your /var/log/secure file for a failed login message with the tty name.  However really you should not be logging in as root. Login as a regular user and then su or sudo to root.

**Comment by KLuka** [comment]
_From [kiryla...@gmail.com](https://code.google.com/u/115616048647944851987/) on June 13, 2012 11:41:54_

Thanks, this helps me too!

**Comment by bsbudhwar** [comment]
Add these lines to /etc/securetty file and enjoy

# Unix98 PTY slaves
pts/0
pts/1
#...

**Comment by riban-bw** [comment]
The port may be higher, e.g. mine was pts/5, then pts/6... Not sure how many pts/x to add to the file or whether you can limit this within the configuration.
