### ISSUE TITLE
vt100.js not working in IE9

### ISSUE THREAD

**Issue by KLuka** [shellinabox/shellinabox#118]
_From [steffen....@gmail.com](https://code.google.com/u/104482245795203483875/) on March 21, 2011 10:43:53_

If used with the just released IE9, vt100.js does not work correctly.

I tracked it down to newCursor.clientHeight not immediately computed inside VT100.prototype.resizer.

While I don't know, why it is not computed and my fix will probably break other things, I got it working for me for now using the modification below. Note, that I only added "false && " in the line with the FIXME comment.

Steffen

\---

VT100.prototype.resizer = function() {
  // The cursor can get corrupted if the print-preview is displayed in Firefox.
  // Recreating it, will repair it.
  var newCursor                = document.createElement('pre');
  this.setTextContent(newCursor, ' ');
  newCursor.id                 = 'cursor';
  newCursor.style.cssText      = this.cursor.style.cssText;
  this.cursor.parentNode.insertBefore(newCursor, this.cursor);
  if (false && !newCursor.clientHeight) { // FIXME This was done to support IE9.
    // Things are broken right now. This is probably because we are
    // displaying the print-preview. Just don't change any of our settings
    // until the print dialog is closed again.
  ...

_Original issue: http://code.google.com/p/shellinabox/issues/detail?id=118_

**Comment by KLuka** [comment]
_From [gomez...@gmail.com](https://code.google.com/u/108362722587442882451/) on August 16, 2011 13:46:31_

I cannot get shellinabox working at all in IE9.  It keeps on writing to a single line at the top and is completely unusable.

This is not a big problem usually, but would be if I wanted to access my server when I only have IE available.

Does anybody know what could be happening?  I am running through HTTPS, if that makes a difference.

**Comment by KLuka** [comment]
_From [bluber...@gmail.com](https://code.google.com/u/107703415970888784053/) on November 07, 2011 03:24:12_

You need to use IE9 compatibility mode. It is under developer tools, push F12 and it is there.

**Comment by KLuka** [comment]
_From [steffen....@gmail.com](https://code.google.com/u/104482245795203483875/) on November 23, 2011 07:16:36_

If you have just a single line, appy the fix I described above.
Also, newer updates of IE9 seem to make scripts containing /*@*/ fail. I replaced them with /* at */ and it works again. Stange.

Sadly, this project seems not to be supported any more.

**Comment by KLuka** [comment]
_From [steffen....@gmail.com](https://code.google.com/u/104482245795203483875/) on November 23, 2011 07:18:26_

Note, /*@*/ occurs twice in vt100.js

**Comment by KLuka** [comment]
_From [ecr...@claimlynx.com](https://code.google.com/u/110950499187810228933/) on June 01, 2012 12:13:29_

For what it's worth, this patch worked well for me.  Thanks!

**Comment by Grimthorr** [comment]
Can this be closed again :smile:?

**Comment by KLuka** [comment]
IE9 still doesn't work ... and I think that won't change in the near future :)

I can't get it to work even in "Compatibility View". I have to use IE8 mode. Fix from first post works until I resize window. But it probably brakes some other stuff for other browsers, as noted by original author.

I will close this for now.
