### ISSUE TITLE
through the browser pasted text looses linebreaks

### ISSUE THREAD

**Issue by KLuka** [shellinabox/shellinabox#129]
_From [lehmi...@gmail.com](https://code.google.com/u/107131456651471362936/) on August 04, 2011 19:29:19_

What steps will reproduce the problem? 1. open shellinabox on server and login
2. open vi with new document
3. copy a simple text containing linebreaks on the client system to the clipboard, for example:

\<table>
\<tr>
\<td>
foobar
\</td>
\</tr>
\</table>

Switch back to shellinabox in your browserwindow (don't forget to press "i" in vi to start editing).
Paste the clipboard to shellinabox by clicking the menu item "paste" in the browser menu (under "edit", I guess). What is the expected output? What do you see instead? expected:
\<table>
\<tr>
\<td>
foobar
\</td>
\</tr>
\</table>

instead:
\<table> \<tr> \<td> foobar \</td> \</tr> \</table> What version of the product are you using? On what operating system? Client: Firefox 5.0, Windows XP SP3
Server: Debian 6, shellinabox 2.10 Please provide any additional information below.

_Original issue: http://code.google.com/p/shellinabox/issues/detail?id=129_

**Comment by KLuka** [comment]
_From [lehmi...@gmail.com](https://code.google.com/u/107131456651471362936/) on August 04, 2011 10:32:25_

Someone issued this already ( issue #56 ).

Sorry...

**Comment by KLuka** [comment]
_From [beewoo...@gmail.com](https://code.google.com/u/107611011494747666553/) on March 31, 2012 15:35:41_

**Status:** Duplicate  
**Mergedinto:** 56

**Comment by emrothenberg** [comment]
I managed to fix this by replacing all \n with \r in gedit before pasting from browser
