### ISSUE TITLE
The symlinks and prefixes are correct for the CSS files, but SiaB starts in Monochrome mode.

### ISSUE THREAD

**Issue by KLuka** [shellinabox/shellinabox#138]
_From [gomez...@gmail.com](https://code.google.com/u/108362722587442882451/) on September 25, 2011 01:56:17_

This issue has only started recently, while it was working fine before, for weeks.

Now when I start it, it appears to be in Monochrome mode, even though Colour Terminal is ticked in the context menu.

If I select Colour Terminal (which is already ticked) it does to colour mode, as it should be in the first place.

It happens every time, and from any computer or browser I use.

I doubt this has any relevance, but I have set the symlink prefixes to have White on Black as the default, as well as Colour Terminal.

I have not knowingly changed anything before this started happening and it was working fine for weeks.

_Original issue: http://code.google.com/p/shellinabox/issues/detail?id=138_

**Comment by KLuka** [comment]
_From [gomez...@gmail.com](https://code.google.com/u/108362722587442882451/) on September 24, 2011 17:41:09_

I've changed the symlink prefixes around to Black on White and SiaB does not start with that option either, even though it is ticked.  I have to select it again before it comes into effect.

**Comment by tickelton** [comment]
This issue also appeared at one of my sites just today.
The host has not been touched for a couple of days and SITB ran fine for weeks.
When I logged in earlier today, unexpectedly the default theme was white-on-black/monochrome instead of the previous (and ticked in the menu) black-on-white/color.

**Comment by a-detiste** [comment]
I've got this freqently too, I just deleted the monochrome css, not a real solution :wink:

**Comment by KLuka** [comment]
I saw this too. But I haven't figure out when or why it happens :) Maybe it has something to do with cookie parsing/handling. 
```
console.log(document.cookie);
"shellInABox=467306938:1110101010"
```
Ones and zeroes represent ticked/unticked context menu options. I will investigate this further...

**Comment by a-detiste** [comment]
Here I guess the culprit is BlueCoat proxy, that does entreprise-wide MITM SSL attack & mangle the pages in various ways.

**Comment by KLuka** [comment]
@a-detiste, @tickelton I found first mistake in reading user CSS settings from cookie. This may be related to your problems. Can you test this patch:

```diff
diff --git a/shellinabox/vt100.jspp b/shellinabox/vt100.jspp
index 2786424..f7a403e 100755
--- a/shellinabox/vt100.jspp
+++ b/shellinabox/vt100.jspp
@@ -329,7 +329,7 @@ VT100.prototype.getUserSettings = function() {
       this.disableAlt       = settings.charAt(5) != '0';
       if (typeof userCSSList != 'undefined') {
         for (var i = 0; i < userCSSList.length; ++i) {
-          userCSSList[i][2] = settings.charAt(i + 5) != '0';
+          userCSSList[i][2] = settings.charAt(i + 6) != '0';
         }
       }
     }
```

**Comment by tickelton** [comment]
@KLuka I rolled out a version with your patch on some of my machines.
Looks fine so far. In the past I haven't seen the error immediately after a restart, though.
I'll keep an eye on it and let you know if it occurs again.

**Comment by KLuka** [comment]
@tickelton that would be great, thanks :+1:

**Comment by tickelton** [comment]
@KLuka it happened again.
Same machine as this morning. All others still work fine, although I did the exact same thing on all of those.

Some additional information:
The machine that I experienced the Problem on is a ubuntu 14.04 VM hosted in some datacenter.
SIOB is only listening on localhost and accessed via apache as a reverse proxy.

What I did before the error occurred:
* logged in from firefox
* closed firefox and deleted cookies
* opened firefox again and opened 2 concurrent sessions
* closed tabs
* opened chromium with recently cleaned data. No pre-existing cookies or history.

The chromium session immediately delivered the wrong CSS.

**Comment by KLuka** [comment]
Hmmm, this tells us that the problems are not in cookies... I will have to investigate further and try to reproduce the issue on my PC.

Could you execute this command in JS console (developer tools) and paste the output, when this happens:
```
userCSSList.toString();
```

**Comment by tickelton** [comment]
Here is the result:

    > userCSSList.toString();
    <- "Black on White,true,true,White On Black,false,false,Color Terminal,true,true,Monochrome,false,false"

**Comment by tickelton** [comment]
I just saw that in the case of the wrong color scheme the spans containing console lines inherit their color from div#scrollable whereas when the color is correct they don't. (See attaches screenshots).

![Uploading Screenshot - 12.05.2015 - 21:32:07_blurred.png…]()
![Uploading Screenshot - 12.05.2015 - 21:32:52_blurred.png…]()

**Comment by tickelton** [comment]
I just saw that in the case of the wrong color scheme the spans containing console lines inherit their color from div#scrollable whereas when the color is correct they don't. (See attaches screenshots).

![screenshot - 12 05 2015 - 21 32 07_blurred](https://cloud.githubusercontent.com/assets/11227292/7596681/db6862c6-f8ef-11e4-9b39-e46b4d62f6a4.png)
![screenshot - 12 05 2015 - 21 32 52_blurred](https://cloud.githubusercontent.com/assets/11227292/7596682/db71c6f4-f8ef-11e4-8936-c450019ba2c3.png)

**Comment by KLuka** [comment]
Thanks for the info, but I am still unable to reproduce or find source of the problem on my Ubuntu 14.04.2 installation... I will have to try harder...

**Comment by KLuka** [comment]
Ok, I just got this :) Actual theme was "White On Black" with "Monochrome" and userCSSList was like this: 
* Black on White,true,true
* White On Black,false,true
* Color Terminal,true,false
* Monochrome,false,true

This happened on first login after debian package reinstallation with Firefox browser...

![shellinabox](https://cloud.githubusercontent.com/assets/1918763/7611163/d1edc996-f982-11e4-8572-f24a5e7c1dbe.png)

**Comment by tickelton** [comment]
>The default settings are not applied correctly in JS. Default debian settings should be "Black On White", but even with official package we get "White on Black" setting with check mark on the "Black On White". Am I seeing this correctly? 

That is exactly what I am observing, too.

After debugging a little more it looks to me as follows:
All the DOM on the client side seems to be correct. userCSSList looks just as expected and the `<link...` tags for the user stylesheets are created correctly.
But for some reason the `disabled` property of the disabled stylesheets is not honored sporadically.

In Chrome i can just keep reloading the same page and sporadically the styles will change.

If i just toggle the disabled property of the `link` tags after the initial page has loaded, either from a console or directly via a timer, everything look as expected.

As far as i can see, the `disabled` property is not modified any more after the initial creation, unless a menu item is clicked. Therefore I believe there is some kind of race condition or other dependency I am not aware of that prevents the property from taking effect.

**Comment by a-detiste** [comment]
> Default debian settings

The init script currently implement this, I have no idea what's supposed to do.

```
  eval start-stop-daemon --start --oknodo --pidfile "'$PIDFILE'"              \
                    --exec "'$DAEMON'" -- -q --background="'$PIDFILE'"        \
                    -c "'${SHELLINABOX_DATADIR}'" -p "'${SHELLINABOX_PORT}'"  \
                    -u "'${SHELLINABOX_USER}'" -g "'${SHELLINABOX_GROUP}'"    \
                    $(for i in $(ls /etc/shellinabox/options-enabled/*.css |
                                 sed -e                                       \
                                    's/.*[/]\([0-9]*\)[-_+][^/:,;]*[.]css/\1/'|
                                 sort -u); do
                        for j in /etc/shellinabox/options-enabled/"$i"*.css; do
                          echo -n "$j" |
                          sed -e 's/\(.*[/]\)\([0-9]*\)\([-_+]\)\([^/:,;]*\)[.]css/\4:\3\1\2\3\4.css,/
                                  s/:_/:-/'
                        done |
                        sed -e 's/,$/;/'
                      done |
                      sed -e 's/;$//
                              //b
                              s/.*/--user-css "\0"/')                         \
                    "${SHELLINABOX_ARGS}"
```

Other distro ships a much more readable systemd service:
* https://aur.archlinux.org/packages/shellinabox/ (dl tarball)
* http://rpmfind.net/linux/rpm2html/search.php?query=shellinabox

**Comment by a-detiste** [comment]
... and this is there since https://github.com/shellinabox/shellinabox/commit/e3a4eb95e3a64e7aa4aa280e80266f9708c0a467

**Comment by KLuka** [comment]
@tickelton You are correct, this really is a race condition. Thanks :+1: 

We have problems because we try to disable unloaded CSS style sheet. I am working on a patch (against running PR #300) and will release it there. For now I have patch bellow and it works for me in Chrome, FF and Opera. Could you also test this on your machines?

```diff
diff --git a/shellinabox/vt100.jspp b/shellinabox/vt100.jspp
index 0689f9f..3ac9db3 100755
--- a/shellinabox/vt100.jspp
+++ b/shellinabox/vt100.jspp
@@ -375,7 +375,16 @@ VT100.prototype.initializeUserCSSStyles = function() {
         style.setAttribute('rel',          'stylesheet');
         style.setAttribute('type',         'text/css');
         document.getElementsByTagName('head')[0].appendChild(style);
-        style.disabled                   = !enabled;
+
+        // If stylesheet needs to be disabled we have to do that from onload
+        // event, otherwise 'disabled' attribute will be ignored.
+        if (!enabled) {
+          style.onload                     = function (style) {
+            return function () {
+              style.disabled               = true;
+            }
+          }(style);
+        }
       }

       // Add entry to menu
```

I am trying to improve cross browser support, because onload event is not supported everywhere...

@a-detiste Yeah this is a mess :smile: As I can tell from `ps` command shellinabox on debian is started with this command line:

```
/usr/bin/shellinaboxd -q --background=/var/run/shellinaboxd.pid -c /var/lib/shellinabox -p 4200 -u shellinabox -g shellinabox --user-css Black on White:+/etc/shellinabox/options-enabled/00+Black on White.css,White On Black:-/etc/shellinabox/options-enabled/00_White On Black.css;Color Terminal:+/etc/shellinabox/options-enabled/01+Color Terminal.css,Monochrome:-/etc/shellinabox/options-enabled/01_Monochrome.css --no-beep
```
So I think that default options for CSS should be "Black On White" and "Color Terminal"...

**Comment by a-detiste** [comment]
Ok, I've got a working .service file; need to dig the --user-css option more
Arch users would need to `sed -i '/ssh/sshd/'`

```
[Unit]
Description=Serve a login-terminal over http on port 4200.
Documentation=man:shellinaboxd(1)
Requires=ssh.service
After=ssh.service

[Service]
WorkingDirectory=/var/lib/shellinabox
ExecStart=/usr/bin/shellinaboxd -p 4200 -u shellinabox -g shellinabox --user-css "White On Black:-/etc/shellinabox/options-enabled/00_White On Black.css;Color Terminal:+/etc/shellinabox/options-enabled/01+Color Terminal.css" --no-beep
ExecReload=/bin/kill -HUP $MAINPID
KillMode=process
Restart=on-abort

[Install]
WantedBy=multi-user.target
```

**Comment by a-detiste** [comment]
the rpm makes it more simple:

```
# OPTS="--user-css Normal:+black-on-white.css,Reverse:-white-on-black.css --disable-ssl-menu -s /:LOGIN"
```

The .service could include several disabled `ExecStart=`so users could overide this service 
in /etc/systemd/system if they want and keep the preset of their choice.

It's just a quick edit with `sudo systemctl edit shellinabox --full` with systemd in Debian/experimental that will land in Sid when 8.1 is released.

**Comment by KLuka** [comment]
@a-detiste I am not really familiar with this service file. It this related to the issue #263. If it is we can continue discussion over there :)

For the `--user-css` options the format is like this: `{label}:{default}{path},{label}:{default}{path};`
* label: human readable label in context menu (right click)
* default: '+' symbol marks the default option, other options in group must have '-' symbol
* path: path to CSS file

Options in context menu group are separated with ',' symbol and groups are separated with ';' symbol...

Hope that helps :)

**Comment by tickelton** [comment]
@KLuka PR #300 seems to solve this issue properly.
I cannot reproduce the issue in Chromium any longer.
As it happened in Firefox much more sporadically and I can currently not reproduce the problem there with older versions, I'll just have to assume it works there, too.
But judging from my previous observations and the way you solved this I am very confident that this is a proper solution (especially as I was about to try out a very similar fix, right as you posted yours :wink:).

**Comment by KLuka** [comment]
@tickelton Hehe, and thanks for help :smile:

Closing this as solved :)
