### ISSUE TITLE
When starting shellinaboxd, I always get the erroro message "Failed to find any available port"

### ISSUE THREAD

**Issue by KLuka** [shellinabox/shellinabox#142]
_From [olaf.tri...@gmail.com](https://code.google.com/u/102594234639137315494/) on October 01, 2011 16:41:29_

What steps will reproduce the problem? 1. When running under root "shellinaboxd" I always get the erroro message "Failed to find any available port". What do I have to do to make sellinabox work? What is the expected output? What do you see instead? That the shellinabox demon would start What version of the product are you using? On what operating system? ShellInABox: shellinabox_2.10-1_amd64.deb
OS: Debian Lenny v5.0 54bit Please provide any additional information below.

_Original issue: http://code.google.com/p/shellinabox/issues/detail?id=142_

**Comment by KLuka** [comment]
_From [gomez...@gmail.com](https://code.google.com/u/108362722587442882451/) on October 02, 2011 06:23:43_

As far as I understand it, that way you are attempting to run SiAB without of the required parameters.  Try this instead:

/etc/init.d/shellinabox  start

...which will start it with the options defined in that script.  I have asked a question here regarding the best way to set different options, but I have never got an answer, so I edit that script directly.

**Comment by KLuka** [comment]
_From [M4dH4TT3...@gmail.com](https://code.google.com/u/107218907350916409736/) on December 18, 2014 05:41:31_

I get this error currently and its  not because of how im starting it!

**Comment by KLuka** [comment]
This error means that some other application is already listening on port 4200.

**Comment by magdesign** [comment]
Just start it on another port:  `shellinaboxd --disable-ssl --port 4222`
and make sure the port is open in the firewall

**Comment by matiasw** [comment]
I am also having this problem.

I am using Debian 11, ShellInABox version 2.20 (revision 4f0ecc3) and the `firewalld` firewall application. In its rules, I have port 4200 open: ` sudo firewall-cmd --list-all
[...]
  ports: 3000/tcp 4200/tcp
`

Indeed, the other port set this way is open and receiving traffic. So why can't SIAB run on its port 4200, even if I explicitly specify this on startup with `--port`?
