### ISSUE TITLE
on-screen keyboard icon not visible if background set to black  (with fix!)

### ISSUE THREAD

**Issue by KLuka** [shellinabox/shellinabox#173]
_From [harry.pe...@gmail.com](https://code.google.com/u/103754021749853863569/) on April 04, 2012 13:51:32_

What steps will reproduce the problem? 1. switch on onscreen keyboard icon with right-click menu
2. switch colours to white on black
3. icon disappears!

This is due, as far as we can tell, to the fact that the icon uses loads of transparency / alpha channel.

Here's a fix:  a different icon!  See attachment. imho a nicer one too.  License is free for commercial reuse

_Original issue: http://code.google.com/p/shellinabox/issues/detail?id=173_

**Comment by KLuka** [comment]
_From [harry.pe...@gmail.com](https://code.google.com/u/103754021749853863569/) on April 04, 2012 04:52:55_

Source for keyboard icon, including license (which says you have to "direct people to their website, not redistribute") http://www.iconfinder.com/icondetails/40804/128/keyboard_icon

**Comment by KLuka** [comment]
_From [beewoo...@gmail.com](https://code.google.com/u/107611011494747666553/) on April 05, 2012 11:56:37_

Nice icon.  My read of the licensing terms does not suggest that we can use it because we would
be redistributing it.  They have licensed it for use on website where it is shown to users, but not
included in distributed files.

Let us know if you find one with an agreeable license.

**Status:** Accepted

**Comment by Grimthorr** [comment]
This can be fixed by applying [f572a57](https://github.com/JGRennison/shellinabox/commit/f572a574e067f5ca7908599d725ebf9177898e25).

**Comment by KLuka** [comment]
@Grimthorr thanks again :)

I applied above patches on my local clone, but I cannot get it to work. I also cloned JGRennison repo and I have the same problems. 

Can you tell how do you get it to work or how to test this? For testing I am using command below and
then I switch to dark background from context menu. Keyboard icon is not visible, but I can click on it. 

```
./shellinaboxd --debug --user-css "White On Black:-/etc/shellinabox/options-enabled/00_White On Black.css;Color Terminal:+/etc/shellinabox/options-enabled/01+Color Terminal.css"
```

**Comment by KLuka** [comment]
Maybe we could just change/fix original image `shellinabox/keyboard.png` to work with both backgrounds.

What do you think?

**Comment by Grimthorr** [comment]
> I applied above patches on my local clone, but I cannot get it to work. I also cloned JGRennison repo and I have the same problems.

Hmm, maybe I was using the CSS file outside of the build, something like:
```
./shellinaboxd --css=white-on-black.css
```

Is the default colour scheme black-on-white?

> Maybe we could just change/fix original image shellinabox/keyboard.png to work with both backgrounds as was suggested in comments above?
> 
> What do you think?

Sounds good, [this](https://gist.github.com/Grimthorr/3ca3896f7402248b18cf) should work; I just removed the transparency.

**Comment by KLuka** [comment]
Thanks :+1: This fix works great even, if user changes background dynamically from context menu. I will commit changes today.

Light background preview:

![light](https://cloud.githubusercontent.com/assets/1918763/6571545/b9f43786-c709-11e4-8e0d-4610f88f94e4.png)

Light background preview:

![dark](https://cloud.githubusercontent.com/assets/1918763/6571547/c18a7ae6-c709-11e4-8b5f-c129b0ae08f1.png)
