### ISSUE TITLE
multiline links

### ISSUE THREAD

**Issue by KLuka** [shellinabox/shellinabox#198]
_From [math...@gmail.com](https://code.google.com/u/103069956538495635880/) on July 27, 2012 11:50:37_

if an URI goes over multiple line, only the part on the first line is transformed into a link and this link is truncated

_Original issue: http://code.google.com/p/shellinabox/issues/detail?id=198_

**Comment by a-detiste** [comment]
I guess this one should be `wontfix`, linkify is just an heuristic to make life easier, not an hard warranty that the links really point to something.

**Comment by KLuka** [comment]
You are correct :+1: Closing this.
