### ISSUE TITLE
Add support for belgian keyboard

### ISSUE THREAD

**Issue by KLuka** [shellinabox/shellinabox#207]
_From [ghpi...@gmail.com](https://code.google.com/u/105297251364130227730/) on October 16, 2012 08:54:09_

What steps will reproduce the problem? 1. Use a belgian keyboard
2. keys not working ")°", "-_", "$*]", ":/", "ù&#37;´", "<>\"
3. keys partially working "^¨[", What is the expected output? What do you see instead? The same character as is printed on the key.  Nothing. What version of the product are you using? On what operating system? 2.14 (build from source)  on Debian amd64 Please provide any additional information below. A number of keys on a belgian keyboard have 3 characters, the third one is obtained in combination with the "Alt Gr" key, acting as a "modifier" or "shift".  
If someone can give me some hints about how to change the js, I could try it myself.

_Original issue: http://code.google.com/p/shellinabox/issues/detail?id=207_

**Comment by KLuka** [comment]
_From [mjacqu...@gmail.com](https://code.google.com/u/112218375234996705991/) on January 10, 2014 05:11:24_

Solution: patch for vt100.h to add the unrecognised keys for the "Belgian French" keyboard:

2933a2934,2941
\>   // Belgian French keyboard conflicts
\>   // : - \< ) $
\>   // : 58
\>   // \< 60
\>   // $ 164
\>   // ù 165
\>   // ) 169
\>   // - 173
2946c2954,2960
\<     event.keyCode == 226;
\---
\>     event.keyCode == 226 ||
\>     event.keyCode == 58 ||
\>     event.keyCode == 60 ||
\>     event.keyCode == 164 ||
\>     event.keyCode == 165 ||
\>     event.keyCode == 169 ||
\>     event.keyCode == 173;

I made the change to the vt100.h file starting from the shellinabox-2.14.tar.gz source archive and built the binary.
However I had some issues in the deployment of shellinaboxd, so I switched to retrofitting the above changes in the ShellInABox.js file from version 2.14 and serving it with the --static-file option.

I can confirm that, with the above changes, it works fine with my Belgian French keyboard.

Michel

**Comment by KLuka** [comment]
This was fixed with 3570f20b0b0db1909bf19685128ed3ae3a3445dd

**Comment by a-detiste** [comment]
Confirming this ! :smile: Finally got tilde & back-quotes working.

Minor nit pick: `Alt-Gr + tilde + space` should gives you a tilde but gives a tilde + an extraneous space;
same problem for the backquote.

**Comment by a-detiste** [comment]
I got the tilde issue on chrome 42 on linux, but not on chrome 40 on WinXP.

**Comment by KLuka** [comment]
Is this the issue with additional space or you can't even type it?

**Comment by a-detiste** [comment]
I just need to remove the extra space, still less disruptive that using Paste From Browser like before; 

I would even say 'it works for me' now because this only happens in my Siab 'test environment' where I can use plain ssh, but not where I actually use it, still you may want to investigate this further for other users.
