### ISSUE TITLE
login: FATAL: can't reopen tty: No such file or directory

### ISSUE THREAD

**Issue by KLuka** [shellinabox/shellinabox#222]
_From [mikael.m...@gmail.com](https://code.google.com/u/112491034291722152299/) on February 21, 2013 23:53:22_

What steps will reproduce the problem? 1. run shellinabox -t
2. browse http://localhost:4200/ What is the expected output? What do you see instead? Most of the time I just get a Session closed, but about 1 in 5 times i acctually get to the login prompt. What version of the product are you using? On what operating system? 2.14 on archlinux. Please provide any additional information below. Feb 21 23:44:33 define login[19710]: FATAL: can't reopen tty: No such file or directory
Feb 21 23:44:35 define login[19711]: FATAL: can't reopen tty: No such file or directory
Feb 21 23:44:35 define login[19712]: FATAL: can't reopen tty: No such file or directory
Feb 21 23:44:36 define login[19713]: FATAL: can't reopen tty: Input/output error
Feb 21 23:44:36 define login[19714]: FATAL: can't reopen tty: Input/output error
Feb 21 23:44:37 define login[19716]: FATAL: can't reopen tty: No such file or directory
Feb 21 23:44:38 define login[19718]: FATAL: can't reopen tty: Input/output error
Feb 21 23:44:39 define login[19719]: FATAL: can't reopen tty: No such file or directory

_Original issue: http://code.google.com/p/shellinabox/issues/detail?id=222_

**Comment by KLuka** [comment]
_From [Sean....@gmail.com](https://code.google.com/u/100525820164996278467/) on March 05, 2013 07:17:48_

I was able to recreate this on my arch desktop. Perhaps this is caused by the arch /bin/login binary which changes permissions on /dev/pts/[session] immediately upon launch? The Debian version does not change the permissions until after the user logs in. When I change the login program from "/bin/login" to "/bin/bash" the shell pops up every time and I never see this error.

**Comment by KLuka** [comment]
_From [bryan.n...@gmail.com](https://code.google.com/u/117275196029035281042/) on January 28, 2015 11:07:37_

I'm seeing this as well using Fedora 20.  Anyone know how to resolve this?

**Comment by BenjiWiebe** [comment]
I am also seeing this bug on Fedora 21, and it is doing the exact same thing that the first comment here mentions.

**Comment by Lakshmipathi** [comment]
@BenjiWiebe , Can you attach strace to shellinaboxd and post relevant parts here? That might provide more hints.

**Comment by BenjiWiebe** [comment]
@Lakshmipathi It's kind of wierd, I get the same results using a fresh install on Fedora 22, but now I'm not getting the printed error message. Anyways, here is the relevant strace of running 'sudo strace shellinaboxd -t --verbose' on Fedora 22.
[partial_strace.txt](https://github.com/shellinabox/shellinabox/files/58776/partial_strace.txt)

**Comment by Lakshmipathi** [comment]
Sorry, I can't find hits on the strace, can you post the entire log on pastebin.com and share the URL ?

**Comment by KLuka** [comment]
@BenjiWiebe, @Lakshmipathi  from the command `sudo strace shellinaboxd -t --verbose` I assume that LOGIN service is used.

I think that problem happens when shellinaboxd launches `/bin/login` program. On way to confirm/debug this would be to configure shellinabox to run something like: `strace /bin/login`. I didn't try this but it should be possible to change service definition from command line params or in source code.

Do you have SELinux installed/enabled? Is this bug easily reproducible?

**Comment by Lakshmipathi** [comment]
@KLuka KLuka, SELinux is a good guess. @BenjiWiebe  Please disable selinux 'setenforce 0' and then try starting shellinaboxd.

**Comment by BenjiWiebe** [comment]
@KLuka, @Lakshmipathi SELinux is disabled on all of my computers. Also, I'm not sure that /bin/login has anything to do with it. From what I have been trying, the problem seems to be that the session key is not getting created/stored in the hash map.

**Comment by KLuka** [comment]
Oh, but I think that errors like `login[19712]: FATAL: can't reopen tty: No such file or directory` are related to `/bin/login`. Do you notice any similar errors in system log files (/var/log/messages, etc...)?

Also you should see the session keys in debug output, maybe this can help you...

**Comment by BenjiWiebe** [comment]
@KLuka Strangely enough, I'm not getting those FATAL can't reopen tty messages anymore. But I am still getting the Session Closed repeatedly...

**Comment by BenjiWiebe** [comment]
@KLuka The thing is, I'm getting the FATAL error when running it as a systemd service, but when I run the same command as root in the terminal, I still get the Session closed but I don't get the FATAL error. Are the two issues related then, or not?

**Comment by BenjiWiebe** [comment]
@KLuka I'm pretty much stuck. If I strace login, it hangs because of a SIGTTOU. If I put a delay before login (so I can attach strace by PID), then I never get the FATAL error, even though I still get a session closed error.

**Comment by Lakshmipathi** [comment]
I think there is some problem with 'login' command itself. I ran into similar issue
with other emulator (tty.js) : http://unix.stackexchange.com/questions/157106/login-command-not-prompting-for-username-password	 sometime back. 

As a root, please try to run shellinaboxd without systemd and see whether it works or not.

**Comment by KLuka** [comment]
@BenjiWiebe I am out of ideas... Does session error happen every time or are you able to connect to system sometimes? Could you paste debug output?

I will install Fedora 22 in VirtualBox and see if I can get similar error.

**Comment by BenjiWiebe** [comment]
@Lakshmipathi If I run SiaB directly as root (without systemd) it never displays the FATAL error, but still always closes the session immediately. It behaves this way even if run without a tty.

**Comment by Lakshmipathi** [comment]
@KLuka  I think something strange happening with recent Linux distro versions for login. After looking at your gist. I think its  pam.d login configuration.
@KLuka @BenjiWiebe  can you try commenting out /etc/pam.d/login entries . I don't know which entry, we need to try trail and error method. Let me check this some time tomorrow.

**Comment by BenjiWiebe** [comment]
@Lakshmipathi I don't think pam.d/sshd applies.

**Comment by BenjiWiebe** [comment]
On a fresh Fedora 20 VM, running SiaB as a systemd service, I get a 'Session closed' maybe 1/5 of the time, due to the line 366 error I linked above. I get the FATAL error from 'login' only occasionally, less than 5% of the time. But I *do* get it occasionally!

**Comment by BenjiWiebe** [comment]
@Lakshmipathi @KLuka Is it OK to chat extensively in the comments here? If not, we could go to Freenode -- pick any channel name.

Anyways, one thing I've found now is that the FATAL error is due to 'login' trying to open the next /dev/pts/N device (in my case, '/dev/pts/3' since 1 and 2 are being used) and apparently /dev/pts/3 hasn't been "allocated" yet. That would be a SiaB problem, no?

**Comment by KLuka** [comment]
@BenjiWiebe @Lakshmipathi I am sorry for late response. Also I made a mistake about `login` issues, since they are documented on man page under BUGS section (recursive login). They have nothing to do with our issue.

@BenjiWiebe you are probably correct that this is in fact shellinabox issue. For now my best guess would be to examine `forkPty()` function and see what is happening there when we get the error. I hope I manage to get a bit more time this during this week...

PS: we can continue discussion on Gitter chatroom (https://gitter.im/shellinabox/shellinabox).

**Comment by KLuka** [comment]
**Update:** Some `/bin/login` implementations close and reopen all ptys on initialization. Since the pty is monitored by shellinabox we receive `POLLHUP` event (depends at what time we start to monitor the pty) and also close the pty. Therefore we get the described errors...

PR #357 should greatly reduce the chances, but if anyone can still reproduce similar error please report here.

**Comment by thatscode** [comment]
I have got several nginx proxy servers before the shellinabox-server.
when I occured POLLHUP error when I try to deploy the  shellinabox-server.

the version I am using is 2.20
I installed via source code
the platform info: CentOS 6.8, kernel version:2.6.32-642.el6.x86_64

the starting command is 
`/usr/local/bin/shellinaboxd -d -t -u root -g root -p my-listening-port --disable-peer-check -s /:SSH:my-server-domain-name`

the error message is bellow:
```
[http] Closing connection to 192.168.0.222:33160
[server] POLLHUP received on PTY! Closing session QeA6IZgd9x6ThzZcT8K7sg!
[server] Session QeA6IZgd9x6ThzZcT8K7sg done.
[server] Child 3008 exited with exit code 255.
[http] Accepted connection from 192.168.0.222:63898
[http] Handling "POST" "/?"
[server] Failed to find session: QeA6IZgd9x6ThzZcT8K7sg
```

PS: 192.168.0.222 is one ip address of my nginx proxies.

**Comment by PandaWuu** [comment]
> I have got several nginx proxy servers before the shellinabox-server. I occured POLLHUP error when I try to deploy the shellinabox-server.
> 
> the version I am using is 2.20 I installed via source code the platform info: CentOS 6.8, kernel version:2.6.32-642.el6.x86_64
> 
> the starting command is `/usr/local/bin/shellinaboxd -d -t -u root -g root -p my-listening-port --disable-peer-check -s /:SSH:my-server-domain-name`
> 
> the error message is bellow:
> 
> ```
> [http] Closing connection to 192.168.0.222:33160
> [server] POLLHUP received on PTY! Closing session QeA6IZgd9x6ThzZcT8K7sg!
> [server] Session QeA6IZgd9x6ThzZcT8K7sg done.
> [server] Child 3008 exited with exit code 255.
> [http] Accepted connection from 192.168.0.222:63898
> [http] Handling "POST" "/?"
> [server] Failed to find session: QeA6IZgd9x6ThzZcT8K7sg
> ```
> 
> PS: 192.168.0.222 is one ip address of my nginx proxies.

@thatscode I got same error on Centos 6.9, could you tell me if this issue has been resolved?

**Comment by abcbarryn** [comment]
This invocation used to work on my old system:

/usr/bin/shellinaboxd -t --localhost-only -u shellinabox -s /ssh:SSH -s /phantasia:phantasia:games:/var/empty:/usr/bin/phantasia --user-css Normal:+white-on-black.css,Reverse:-black-on-white.css

Both the /ssh and the /phantasia worked. On my new Linux only /ssh works. The /phantasia service does this:
```
[http] Accepted connection from localhost:42754
[http] Handling "POST" "/phantasia/?"
[server] Creating a new session: IKhp0SHiPRxBjUFJyluy/g
[server] Child 44712 launched
[server] Window size changed to 133x40
[http] localhost - - [04/Jul/2025:23:35:07 -0400] "POST /phantasia/? HTTP/1.1" 200 157
[http] Handling "POST" "/phantasia/?"
[server] POLLHUP received on PTY! Closing session IKhp0SHiPRxBjUFJyluy/g!
[server] Session IKhp0SHiPRxBjUFJyluy/g done.
[http] localhost - - [04/Jul/2025:23:35:07 -0400] "POST /phantasia/? HTTP/1.1" 200 157
[server] Child 44712 exited with exit code 1.

```
The directory /var/empty exists and is 755 mode. The executable /usr/bin/phantasia is mode  4755. The user phantasia has a shell of /usr/bin/phantasia and logging in as phantasia or su - phantasia works.
