### ISSUE TITLE
Allow white-on-black color theme

### ISSUE THREAD

**Issue by KLuka** [shellinabox/shellinabox#24]
_From [nigel.ta...@gmail.com](https://code.google.com/u/114501845987868689003/) on July 14, 2009 16:59:25_

I just prefer my shells to have white text on a black background than black 
text on a white background.

Patch attached for a new --white-on-black command line flag, which can be 
overridden in the JavaScript by setting the global whiteOnBlack variable to 
true or false.

**Attachment:** [shellinabox-whiteonblack.patch](http://code.google.com/p/shellinabox/issues/detail?id=24)

_Original issue: http://code.google.com/p/shellinabox/issues/detail?id=24_

**Comment by KLuka** [comment]
_From [zod...@gmail.com](https://code.google.com/u/109388341641331418132/) on July 14, 2009 09:00:39_

Thank you for the patch. I'll have to think about this a little bit. The recommended
approach is generally that you should use the -f option to provide an alternative CSS
style file. But for simple tweaks such as changes in color, there probably needs to
be an easier solution.

**Comment by KLuka** [comment]
_From [nigel.ta...@gmail.com](https://code.google.com/u/114501845987868689003/) on July 14, 2009 17:04:03_

Ah, I didn't realize that you could -f style.css:whiteonblack.css. Maybe a better 
solution is to simply check in a separate whiteonblack.css file that has, for example, 
small additions like "#vt100 { background-color: black; }".

**Comment by KLuka** [comment]
_From [zod...@gmail.com](https://code.google.com/u/109388341641331418132/) on July 30, 2009 10:50:49_

I just checked in revision `#158` , which has a new "--css" command line option. The 
manual page describes how to use that option to enable white-on-black mode. Please let 
me know, if you encounter any difficulties with this new option.

**Status:** Fixed

**Comment by KLuka** [comment]
_From [gnute...@gmail.com](https://code.google.com/u/111345694547719922573/) on July 30, 2009 16:53:52_

Is there the chance to make this a per-session option, rather than at start time?  I 
like black on white, but another user of my system likes white on black.

How about a right-click option to select a CSS or a style?

**Comment by KLuka** [comment]
_From [zod...@gmail.com](https://code.google.com/u/109388341641331418132/) on July 30, 2009 18:00:19_

Let me think about this for a while. I didn't really anticipate the need of per-user
style sheets. I'll have to see how this could be done cleanly.

**Status:** Accepted

**Comment by KLuka** [comment]
_From [zod...@gmail.com](https://code.google.com/u/109388341641331418132/) on July 31, 2009 14:16:15_

I think, I have some general idea of how user selectable style sheets should be done
cleanly. Unfortunately, that'll require a little more work to get right.

In the meantime, the best suggestion is to provide alternative URLs for different
pre-defined style sheets. Something like the following should work:

shellinaboxd -s /:LOGIN -s /white-on-black:LOGIN -f
/white-on-black/styles.css=styles-white-on-black.css

You would then have to create a suitable styles-white-on-black.css file by
concatenating the existing styles.css and white-on-black.css files.

Users can then go to either the default URL, or the /white-on-black URL. This
mechanism can be extended for arbitrary other style changes (e.g. monochrome mode,
bigger/smaller fonts, different cursor color, ...)

Please let me know, if this works as a stop-gap measure until I find the time to
implement a more flexible solution.

**Comment by KLuka** [comment]
_From [gnute...@gmail.com](https://code.google.com/u/111345694547719922573/) on August 02, 2009 16:20:43_

Thanks, this sounds like a good interim workaround.  Will try.

**Comment by KLuka** [comment]
_From [zod...@gmail.com](https://code.google.com/u/109388341641331418132/) on November 21, 2009 13:02:26_

Fixed in subversion. Use the --user-css option to add new style sheets that customize 
the visual appearance. These style sheets can then be selected by the user by opening 
the right-click context menu.

**Status:** Fixed

**Comment by ruppke** [comment]
bro has an entire convorsation with self

**Comment by ruppke** [comment]
anywho i just wanted to say that shellinabox has no white on black theme, I just checked
