### ISSUE TITLE
Cannot look up group "shellinabox" at service start

### ISSUE THREAD

**Issue by KLuka** [shellinabox/shellinabox#243]
_From [hipi...@gmail.com](https://code.google.com/u/105110001891511221739/) on October 26, 2013 12:04:53_

What steps will reproduce the problem? 1. install shellinabox on Debian 7.2 from repository (apt-get install shellinabox) - works fine
2. after the server reboot, shellinabox was not present - not started automaticaly
3. when tried to run it via "service shellinabox start" the message said:
Cannot look up group "shellinabox". What is the expected output? What do you see instead? correct start of application What version of the product are you using? On what operating system? ShellInABox version 2.10 ( revision 239 )
Debian 7.2 - Linux XXX 3.2.0-4-686-pae `#1` SMP Debian 3.2.51-1 i686 GNU/Linux Please provide any additional information below. how to start shellinabox automaticly with system startup?
The source privileges.c has function about it.

_Original issue: http://code.google.com/p/shellinabox/issues/detail?id=243_

**Comment by KLuka** [comment]
_From [enkidush...@gmail.com](https://code.google.com/u/113865631220550685337/) on February 28, 2014 13:44:44_

I got this same error right after installing shellinabox rather than on system reboot.  I'm not a programmer, so I don't know why this matters (maybe something to do with gr_len in privileges.c), but when I moved the shellinabox group entry to an earlier point in /etc/group (near the top with other system groups), shellinabox starts fine from the command-line or /etc/init.d files.

That said, I haven't tested that it comes up again at reboot (I'm not on a system I can reboot easily).  Perhaps someone could try this on a system where they can test rebooting?

**Comment by KLuka** [comment]
_From [hipi...@gmail.com](https://code.google.com/u/105110001891511221739/) on February 28, 2014 23:24:58_

I found the reason of the error. In my case it was the OS fault (I think), as the group, which SHINBOX belongs to, was after another group, which contains 80 users. So, the problem was, that OS was not able to "access" entry of any group, which followed the "big" users group.
I just moved the "big" entry group at the end of /etc/groups, and everything started correctly.

**Comment by KLuka** [comment]
_From [enkidush...@gmail.com](https://code.google.com/u/113865631220550685337/) on March 13, 2014 09:05:47_

That fits my situation as well, but I wouldn't really say this is an OS issue, since groups with > 80 members shouldn't be a problem.  I think this points again to how gr_len gets set (mabye it needs a larger default?).

**Comment by tickelton** [comment]
The Issue here is that the size of the buffer used in getgrnam_r is determined by querying _SC_GETGR_R_SIZE_MAX.
If that buffer turns out to be to small getgrnam_r will fail.
Older versions of the manpage of getgrnam_r desribed _SC_GETGR_R_SIZE_MAX  as the maximum size of a buffer the function can handle, while actually (and also in newer versions of the man page) that size is only a recommendation but can be increased if it is not sufficient.

I submitted pull request #298 that should solve this issue by treating _SC_GETGR_R_SIZE_MAX as a recommendation and increasing the buffer size dynamically if it turns out to be to small.

**Comment by KLuka** [comment]
Thanks, this fixes the issue :+1:
