### ISSUE TITLE
IE 11 - Can't connect with default compatibility mode.

### ISSUE THREAD

**Issue by KLuka** [shellinabox/shellinabox#262]
_From [mala...@jeffrika.com](https://code.google.com/u/102095524802552049076/) on August 22, 2014 21:40:15_

* What steps will reproduce the problem?

Try to connect to shellinabox from IE 11, browser shows message: "This page can’t be displayed" with no other indication of what went wrong.  Network transfer logs show a single page request with no data.

Enable IE 11 "compatibility mode" in the browser and it connects ok.

* What is the expected output? What do you see instead?

Should be able to connect to shellinabox without setting compatibility mode.

* What version of the product are you using? On what operating system?

Customized shellinabox based on 2.14 code, IE 11 on Windows 8.1.

* Please provide any additional information below.

The problem appears to be with the ieBug detection code in libhttp/httpconnection.c.  The code takes some actions based on finding "MSIE" in the user-agent string.  IE 11 no longer has "MSIE" in the user-agent string, so the ieBug mitigation steps do not run.  Putting IE 11 into "compatibility mode" changes the user-agent string back to one that contains "MSIE", so the ieBug code is triggered, and the connection works in that case.

It's probably not a good idea to have different code paths based on the content of the user-agent string.  A better solution might be to figure out what the shellinabox httpd is doing that IE doesn't like, and fix that for all of the connections.  Until then, here is a change that adds detection for the IE 11 user-agent string "rv:11" to enable ieBug mode.

In file libhttp/httpconnection.c:

@@ -569,7 +593,8 @@
   int ieBug                 = 0;
   const char *userAgent     = getFromHashMap(&http->header, "user-agent");
   const char *msie          = userAgent ? strstr(userAgent, "MSIE ") : NULL;
-  if (msie) {
+  const char *ie1          = userAgent ? strstr(userAgent, "rv:1") : NULL;
+  if (msie || ie1) {
     ieBug++;
   }

_Original issue: http://code.google.com/p/shellinabox/issues/detail?id=262_

**Comment by KLuka** [comment]
_From [willycho...@gmail.com](https://code.google.com/u/115958006148965318637/) on December 25, 2014 01:03:56_

Instead of "rv:1", "Trident" or "Trident/7.0" may be better choices.

"In rare cases, it may be necessary to uniquely identify IE11. Use the Trident token to do so.", mentioned by Microsoft ( http://msdn.microsoft.com/en-us/library/ie/hh869301%28v=vs.85%29.aspx#ie11 )

**Comment by KLuka** [comment]
_From [lfourqu...@gmail.com](https://code.google.com/u/112892845337105890020/) on February 27, 2015 03:27:49_

Instead of making the browser sniffing more complicated, would it not be better to drop it completely and use code that works for all current browsers?

The attached patch does this:
 * switch to gzip encoding (which is consistently implemented by everyone) instead of deflate;
 * drop all the browser sniffing code.

With this patch, shellinabox works in IE11 (tested), and should work in every version of IE since IE7 (not tested).  It won't work any more in IE6 but even Microsoft has been telling everyone to please stop using IE6.

**Attachment:** [shellinabox-gzip.diff](http://code.google.com/p/shellinabox/issues/detail?id=262#hc2)

**Comment by lfourquaux** [comment]
Hello,
I'm the author of the patch "shellinabox-gzip.diff" above.
I would like to point out that by testing for "Trident" instead of "MSIE" you are also breaking compatibility with IE6 _and_ IE7.  (The "Trident" token was introduced in IE8, IIRC).
I still think that my patch is a better idea (and not much of a change), but if you want to keep the browser sniffing logic you should probably test for "MSIE" (IE <11) and for "Trident" (IE >7).

**Comment by KLuka** [comment]
Hi, and thanks for the heads-up :)

I was already thinking about using your patch so I left this issue opened. If you wish and have some time you can submit pull request with your patch and i will merge it. Otherwise i will try to integrate it later this week.

**Comment by Grimthorr** [comment]
Recreated patch for the current repo [here](https://gist.github.com/Grimthorr/62fd9dab639c5de65db1). I agree that swapping to gzip compression at the cost of IE6 support is favourable. I've pushed the patch to [Grimthorr/shellinabox](https://github.com/Grimthorr/shellinabox). Want a pull request?

**Comment by KLuka** [comment]
That would be great :)

**Comment by lfourquaux** [comment]
@Grimthorr @KLuka : thank you!
