### ISSUE TITLE
How Linode makes users to autologin to shellinabox?

### ISSUE THREAD

**Issue by KLuka** [shellinabox/shellinabox#264]
_From [foranyc...@gmail.com](https://code.google.com/u/103730970477278689487/) on September 26, 2014 14:04:12_

Linode users can login to their servers through so called Lish, which is in fact Shell in a box. So I wonder how it is possible to login and manage multiple servers from a single instance of Shell in a box without entering a root password? 

I know I can set destination IP in the configuration file, but it is not ok to change the main configuration file for multi-user environment. 

As for password the https://github.com/anilgulecha/shellinabox/blob/master/README says something about autologin feature. Is it already implemented or that fork on GitHub doesn't have anything with the one on Google Code?

_Original issue: http://code.google.com/p/shellinabox/issues/detail?id=264_

**Comment by KLuka** [comment]
_From [foranyc...@gmail.com](https://code.google.com/u/103730970477278689487/) on September 26, 2014 05:16:14_

In other words, is it possible to do something like https://localhost:4200/?h=google.com&u=root&p=mypassword? Would be perfect if we could indicate various destination hostname directly in a browser's address bar.

**Comment by KLuka** [comment]
_From [vinayabh...@gmail.com](https://code.google.com/u/112207224871482038810/) on January 28, 2015 10:23:42_

Hi
Did you get to know if the auto login feature is enabled? I am also interested in it

**Comment by Grimthorr** [comment]
It's likely that Linode is using a custom build of shellinabox to incorporate such features?

**Comment by KLuka** [comment]
Yeah, and they probably use some special service definition like in example below. But this is really __dangerous__ because, you don't have any authentication and anyone can connect to your box.

```
./shellinaboxd --debug --service /:${USER}:${USER}:${PWD}:bash
```

I am closing this issue for now.
