### ISSUE TITLE
There doesn't seem to be a way to disable SSL 3.0 protocol

### ISSUE THREAD

**Issue by KLuka** [shellinabox/shellinabox#270]
_From [markhric...@gmail.com](https://code.google.com/u/111494908212390941112/) on November 27, 2014 08:33:44_

What steps will reproduce the problem? 1. Go to a test site for SSL certificate: https://www.digicert.com/help 2. Enter your URL for a shellinbox server with SSL support and then click to check the SSL cert. What is the expected output? What do you see instead? It should show a green checkmark for Protocol Support without any warnings. 

Instead it shows this:

SSL 3.0 is an outdated protocol version with known vulnerabilities

This is easy to disable in the apache config file, but I don't see a way in the manual page on how to disable the protocol using shellinabox as a web server. What version of the product are you using? On what operating system? shellinabox-2.14-27.git88822c1.fc19.x86_64 already installed and latest version (on Fedora 19) Please provide any additional information below. For more information on the vulnerability: https://www.digicert.com/cert-inspector-vulnerabilities.htm#ssl_3_protocol_enabled

_Original issue: http://code.google.com/p/shellinabox/issues/detail?id=270_

**Comment by KLuka** [comment]
_From [p...@hughesbox.co.uk](https://code.google.com/u/116021243388841816452/) on November 27, 2014 06:02:24_

Issue 215 has a patch that is supposed to disable SSL 3.0 but it fails to build after applying it (for me); I've attached the log output from make.

**Attachment:** [output.txt](http://code.google.com/p/shellinabox/issues/detail?id=270#hc2)

**Comment by KLuka** [comment]
_From [p...@hughesbox.co.uk](https://code.google.com/u/116021243388841816452/) on December 15, 2014 00:46:34_

A fix for this has been released by JGRennison on GitHub: https://github.com/JGRennison/shellinabox .

**Comment by Grimthorr** [comment]
This was fixed by @JGRennison's commit 490781d998688125505dd56b6b52187644864005 that I see has been merged. Thanks for taking this project on @KLuka :+1:.

**Comment by KLuka** [comment]
@Grimthorr Thanks for the info :)
