### ISSUE TITLE
How to pass credentials to SSH command

### ISSUE THREAD

**Issue by KLuka** [shellinabox/shellinabox#278]
_From [santoshv...@gmail.com](https://code.google.com/u/116571547746659264187/) on February 06, 2015 07:49:36_

Hi all,

Iam running the following command to ssh a particular host. 

shellinaboxd -s /:SSH:<hostip>

Is there any way to pass username and password for that connection to eliminate  entering user and password everytime he/she accesses the url.

Thanks In Advance.

_Original issue: http://code.google.com/p/shellinabox/issues/detail?id=278_

**Comment by Grimthorr** [comment]
Shellinabox doesn't support this (it would be dangerous too).

**NB**: We might be able to close this issue?

**Comment by KLuka** [comment]
I will close this for now. It is somewhat similar to #264

**Comment by shodanx2** [comment]
Is it possible to put my browser's shellinabox public key into authorized_keys of the target server ?
Does the client autogenerate new keys on every page reload ?
Could I have a URL that includes a local private key file ?

(and ultimate version, my browser queries my smart card for private key authorisation, probably using pkcs#11 on a javacardos smartcard/nfc)
