### ISSUE TITLE
shellinaboxd: unrecognized service

### ISSUE THREAD

**Issue by KLuka** [shellinabox/shellinabox#281]
_From [tech@frontrowcomputer.com](https://code.google.com/u/tech@frontrowcomputer.com/) on February 17, 2015 18:52:57_

What steps will reproduce the problem? 1.Installed with Ubuntu Software Centre
2.Ran command in terminal; sudo service shellinaboxd start
3.Received error message; shellinaboxd: unrecognized service

What is the expected output? What do you see instead?Haven't used it before.

What version of the product are you using? On what operating system?2.14-1 on Xubuntu 14.04 Please provide any additional information below.

_Original issue: http://code.google.com/p/shellinabox/issues/detail?id=281_

**Comment by Grimthorr** [comment]
Shellinabox doesn't run as a service; you'll need to use the binary to start it:

```
shellinaboxd -s /:LOGIN
```

This command should start a web server at localhost:4200.

**NB**: Looks like this was installed from the Ubuntu apps directory (is [this](https://apps.ubuntu.com/cat/applications/shellinabox/) it?). This issue can probably be closed.

**Comment by KLuka** [comment]
I think that the problem is with his command line. 

He should be using command `sudo service shellinabox start`, which doesn't have the __d__ on the end of _shellianbox_.
