### ISSUE TITLE
build of last commit failed

### ISSUE THREAD

**Issue by spali** [shellinabox/shellinabox#301]
@KLuka 
last debian build failed of the new commit 371f061279278e05b4b325b4b64c224c5e0e0fad
see: https://drone.io/github.com/shellinabox/shellinabox/28

**Comment by spali** [comment]
Ok works again, had to change the build script to:
```
i="$(dpkg-checkbuilddeps 2>&1 | sed -e 's/.*dependencies: //;t;d')"
[ -n "$i" ] && sudo DEBIAN_FRONTEND=noninteractive apt-get install -y $i
autoreconf -i
dpkg-buildpackage -b
```
see: https://drone.io/github.com/shellinabox/shellinabox/33
and the resulting deb file: https://drone.io/github.com/shellinabox/shellinabox/files

@KLuka by the way, sorry I forgot to add you as member in the builds on https://drone.io, could you register (could be with the github account) and let me know the user name. So I can add you as Admin there.

**Comment by a-detiste** [comment]
I had a bit of trouble with the last commit too, I did this to clean mt git tree:   
`xargs rm '{}' -vi  < .gitignore`

**Comment by a-detiste** [comment]
> had to change the build script to:

I don't see what has been changed. (I use debuild, will try with cowbuilder too)

**Comment by KLuka** [comment]
@spali Nice to hear from you :) I didn't even know that we have this thing running. I created new account on drone.io, name is same as here - KLuka. I also wanted to say that you can add your docker repo for shellinabox to this group, if you think it is ready.

@a-detiste I think he just had to add `autoreconf -i` command.

**Comment by spali** [comment]
That's true, it was just the missing ```autoreconf -i```.

@KLuka you are now admin in the build project. I'm currently a bit busy, but If you have time, it would be cool if you could do the following if you have time:
- integrate the build status banner here in the ```Readme.md```
- And never tried it but found this for Pull request build reporting: http://andrew.yurisich.com/work/2014/08/18/github-pull-request-statuses-with-drone-io/
- Currently only amd64 build will be executed. I tried to script something with debootstrap to build at least a i386 package, but didn't get it to work. Maybe you have more luck.
- Maybe link the build artifacts here or maybe include in the build script to publish it as nightly release on github if it comes from the master branch.

I will check if I can update my docker-shellinabox project to use the code here (currently based on the debian repo package. Then I will add the repo here as an organisation project.

**Comment by a-detiste** [comment]
@KLuka ah ok, I'm not used to build thing manually, I most build thing for inclusion in Debian archive, so debuild / cowbuilder have to work. 

Here's a new PR to let debuild call autoreconf automatically
https://github.com/shellinabox/shellinabox/pull/303
