### ISSUE TITLE
debian: enable parallel build

### ISSUE THREAD

**Issue by a-detiste** [shellinabox/shellinabox#302]
for myself, le'ts make this RaspberryPi 2 sweat !

**Comment by KLuka** [comment]
Hehe, poor Raspberry :smile:  Maybe [this](http://www.linuxquestions.org/questions/linux-software-2/parallel-jobs-with-dpkg-buildpackage-4175502264/) is a valid solution. You just add --parallel in debian/rules and than you have to run dpkg-buildpackage with -j<number-or-jobs> switch?

**Comment by a-detiste** [comment]
90% of the time is wasted by the auto-* stuff, it's not worth it

**Comment by KLuka** [comment]
Closing this as `wontfix` for now...
