### ISSUE TITLE
wrong font ? regression ?

### ISSUE THREAD

**Issue by a-detiste** [shellinabox/shellinabox#307]
I'm trying the new shellinabox.

First I now got a connection at first try !

Previously I had to refresh the page several times to get a prompt. :smile: 

![rc](https://cloud.githubusercontent.com/assets/7994192/7648720/6d6e0e80-fae6-11e4-9ea4-4aa8185e6f45.png)

I see a other font got picked, which is less optimal, is this a regression ?

`mc` display some strange characters at the top, this wasn't the case before.

(client = Google Chrome 40 on Windows XP)

**Comment by KLuka** [comment]
Hm, what kind of font was rendered? You can check it with developer tools in developer tools like this:

![shellinabox](https://cloud.githubusercontent.com/assets/1918763/7648996/1451cb2c-fae9-11e4-84ca-6b8b289efcac.png)

**Comment by a-detiste** [comment]
I've got a mix of those:

title bar: 
```
Courier New—125 glyphs  
Consolas—9 glyphs
```

exit prompt: 
```
Courier New—56 glyphs  
Consolas—2 glyphs  
```

**Comment by KLuka** [comment]
That is strange :) Can you try this patch:

```diff
diff --git a/shellinabox/styles.css b/shellinabox/styles.css
index 23dcf89..03d77be 100755
--- a/shellinabox/styles.css
+++ b/shellinabox/styles.css
@@ -45,7 +45,7 @@
 }

 #vt100 #console, #vt100 #alt_console, #vt100 #cursor, #vt100 #lineheight, #vt100 .hidden pre {
-  font-family:          "DejaVu Sans Mono", "Everson Mono", FreeMono, "Andale Mono", Consolas, monospace;
+  font-family:          "DejaVu Sans Mono", "Everson Mono", FreeMono, "Andale Mono", monospace;
 }

 #vt100 #lineheight {
```

**Comment by a-detiste** [comment]
When I remove Consolas, I got a correct display again. This is maybe because WinXP is full of quirks.

patching the binary works as well.
```
grep Consolas shellinaboxd --binary-files=text   -> one occurence
sed -i 's/Consolas,/         /' shellinaboxd
```

I now see this was added recently: https://github.com/shellinabox/shellinabox/commit/c13170fe337b7812160a1238fef85fc8ad1a428e

**Comment by KLuka** [comment]
Yes, I added this, because it looks good for FF users on windows system. FF doesn't use Consolas as monospaced font by default.

Do you think we should remove it? Or we can find a better solution so that we can keep Consolas in font stack?

**Comment by Grimthorr** [comment]
This is likely because [Consolas](http://en.wikipedia.org/wiki/Consolas) is not included in XP by default. Might be worth adding another font to the end of `font-family` stack that XP does have, like "Lucida Console"?

**Comment by a-detiste** [comment]
Here Consolas is installed, but I got a mix of Consolas & Courrier in the rendering.

**Comment by Grimthorr** [comment]
Does it help if you add `"Courier New"` after `Consolas` in the `font-family` list?

**Comment by Grimthorr** [comment]
We could try adding a web font ([Droid Sans Mono](https://www.google.com/fonts#QuickUsePlace:quickUse/Family:Droid+Sans+Mono) is similar to Consolas), but that might be overzealous for other clients that do support the current font list.

**Comment by a-detiste** [comment]
> Does it help if you add "Courier New" after Consolas in the font-family list?

I get the same problem

**Comment by KLuka** [comment]
I think that your Consolas font installation doesn't contain all the symbols. And than browser falls back to Courier New just for missing symbols... (?)

Could you maybe reinstall Consolas fonts ([download](http://www.fontpalace.com/font-download/Consolas/))? Ohhh, and how does it work with other browsers on XP machine?

I know that proper fix would be to remove Consolas from font stack. I really hope that we find another way :) Regarding Web fonts, I think that they are a bit overkill for this, but we could also try it.

**Comment by a-detiste** [comment]
I'have no admin rights & the other browser is IE6.

Can this be overriden with a --user-css= ?

Another way: well UserAgent sniffing is ugly...

**Comment by a-detiste** [comment]
> I think that your Consolas font installation doesn't contain all the symbols

That's it; when I copy some examples from wikipedia, they show up as broken characters in charmap.

![consolas_xp](https://cloud.githubusercontent.com/assets/7994192/7651583/6e2e9940-fb02-11e4-9b53-429e8d8a2130.png)

**Comment by Grimthorr** [comment]
> > I think that your Consolas font installation doesn't contain all the symbols

> That's it; when I copy some examples from wikipedia, they show up as broken characters in charmap.

Ah, that makes sense. The Consolas font is [licensed](https://www.microsoft.com/typography/fonts/font.aspx?FMID=1924) so you may have a free or restricted version.

**Comment by KLuka** [comment]
For the user-css solution you can do something like this.

```
--user-css="Modern fonts:+{PATH}/fonts-enable.css,Old fonts:-/{PATH}/fonts-disable.css"
```

File fonts-enable contains the same setting as in styles.css, but the file fonts-disable.css must contain:
```css
#vt100 #console, #vt100 #alt_console, #vt100 #cursor, #vt100 #lineheight, #vt100 .hidden pre {
  font-family: monospace;
}
```
This way you can switch fonts from context menu...

**Comment by a-detiste** [comment]
> File fonts-enable.css contains the same font setting as in styles.css,

`+{PATH}/fonts-enable.css` or just `+/dev/null`

Works for me :+1:

**Comment by KLuka** [comment]
Ok, than I will close this as `wont fix`.
