### ISSUE TITLE
Grand Password Authentication only for shellinabox

### ISSUE THREAD

**Issue by clement-escolano** [shellinabox/shellinabox#310]
Hello everyone,

I discovered shellinabox and I am thankful for that, it's great so far !
Though, I usually rsa keys to login (it is much safer than clear text passwords) but it is obviously not working with shellinabox.
I set settings in ssh to accept password authentication again in order to use shellinabox but I would like, if possible, to only grand password authentication when I login inside shellinabox.

I looked on the internet and it appears that it can be possible to to do that with specific IP address(es). So I tried localhost, 127/24 but so far didn't work out. What is strange is that when I type `last` command in a shell, I see that the IP address that shellinabox uses is the hostname. So I tried to replace the IP address by the hostname, with and without quotes, but still didn't work out.

Do you guys have any idea about how to do it ?

Thanks !

Clement

**Comment by clement-escolano** [comment]
Resolved it myself :-) 
In fact, you have to add at the end of you ssh config file :
```
Match host your_hostname
       PasswordAuthentication yes
```
And it works :-)

**Comment by KLuka** [comment]
Hello, thanks of your support and I am glad you resolved the issue by yourself :)

If I understand things correctly you have disabled password authentication for sshd on your system. But because shellinabox cannot use ssh keys this was causing problems. Now you solved the situation by configuring sshd to allow password authentication only from local system.

Please correct me if I am wrong? And thanks for useful information :+1:

**Comment by a-detiste** [comment]
That's material for a new 'LIMITATIONS' paragraph in the man page. :smile:

**Comment by KLuka** [comment]
@a-detiste :smile: yes, that would be good, because other people were having similar issues, like #112 for example...

**Comment by a-detiste** [comment]
SiaB could be even smarter and print a big fat warning in postinst script / at runtime if it see `PasswordAuthentication no` in `/etc/ssh/sshd_config`

**Comment by clement-escolano** [comment]
Glad there are some people thinking it's useful !
@KLuka you are absolutely correct :-)

**Comment by a-detiste** [comment]
I the code, ssh is called forcefulyl with `-oPasswordAuthentication=yes -oRSAAuthentication=no` 
https://github.com/shellinabox/shellinabox/blob/master/shellinabox/service.c#L153

so I guess /etc/ssh/sshd_config didn't matter, but then I don't understand why this bug happens. ???

**Comment by KLuka** [comment]
@a-detiste This is client configuration. File `/etc/ssh/sshd_config` is for server configuration.

When shellianbox connects to localhost, `ssh` client wants to use password, but the server `sshd` is not accepting passwords only public keys...

**Comment by a-detiste** [comment]
Haaa I understand. So reading /etc/ssh/sshd_config if possible and searching for `PasswordAuthentication no` would  actually be usefull.

**Comment by KLuka** [comment]
Yes it would be, but only if shellianbox is started with SSH service.

But I think that this is hard to do correctly. Because you have to parse the whole file and check the settings (like special cases for hosts), and maybe on some systems the file is on some other path, etc...

Maybe there is a easier and more universal way to find this out at run time?

**Comment by clement-escolano** [comment]
I think there is actually one, I don't know how to implement it in C but here's the thing :
when PasswordAuthentication is set to no (and no other specific rules apply), SiaB ask for a username. And if you type any usename (even if it doesn't exist) then SiaB exit and the "Connect" button is displayed.
So SiaB could simulate an authentification and if it is rejected immediately, then we are in this particular case.

**Comment by a-detiste** [comment]
that would polute logs

**Comment by a-detiste** [comment]
ssh give this when trying to connect to a host that only accepts RSA Keys: `Permission denied (publickey).`   
SiaB could simply forward the stderr from failed `ssh`attempt to the web page visitor.

**Comment by KLuka** [comment]
Hm, what happens if we remove `-oLogLevel=quiet` [here](https://github.com/shellinabox/shellinabox/blob/master/shellinabox/service.c#L166)?

**Comment by a-detiste** [comment]
I guess it would work, but I can't test it now, I have only one port avaible (443)

```
pi@raspberrypi ~ $ ssh localhost                                                                         
Permission denied (publickey).                                                                           
pi@raspberrypi ~ $ ssh localhost -oLogLevel=QUIET
pi@raspberrypi ~ $
```

**Comment by a-detiste** [comment]
Or maybe you would settle for ERROR or FATAL instead of INFO (default):
```
LogLevel The possible values are: QUIET, FATAL, ERROR, INFO,
VERBOSE, DEBUG, DEBUG1, DEBUG2, and DEBUG3.
The default is INFO.
```

**Comment by KLuka** [comment]
I tested this in shellianbox with log level FATAL and it works as expected :+1: We should change this and add a solution or a hint in manuals.
