### ISSUE TITLE
Playstation Vita

### ISSUE THREAD

**Issue by a-detiste** [shellinabox/shellinabox#312]
That's a silly request: allways enable virtual keyboard when connecting with PS Vita; 
this device can't right-click.

`Mozilla/5.0 (PlayStation Vita 3.51) AppleWebKit/537.73 (KHTML, like Gecko) Silk/3.2`

**Comment by KLuka** [comment]
Haha :) maybe we could add user agent sniffing somewhere  [here](https://github.com/shellinabox/shellinabox/blob/master/shellinabox/vt100.jspp#L293-L297) and set the `this.softKeyboard` to `true`... I think that should work and it will not mess with other code, so it would be OK :)

Do you actually use shellinabox with PS Vita? If you can test this you could create a PR with solution :)

**Comment by KLuka** [comment]
Latest commit enables keyboard icon by default for PS Vita. But as @a-detiste reported it is still not very useful due to very small screen...
