### ISSUE TITLE
debian: options on upgrade

### ISSUE THREAD

**Issue by a-detiste** [shellinabox/shellinabox#313]
I realized something is just plain wrong in the current Debian package: 

The symlinks in `/etc/shellinabox/options-enabled`should only be created by as maintainer script (postinst ?) on a clean install; and should never been touched on a simple upgrade. 

I had disabled 2 .css and they come back each time I re-install the package; the symlinks staticaly shipped in .deb re-enable unwanted option.

I'll take care of this.

**Comment by KLuka** [comment]
Ok, that would be reasonable.

**Comment by a-detiste** [comment]
reported there too: http://bugs.debian.org/cgi-bin/bugreport.cgi?bug=786441

**Comment by a-detiste** [comment]
this can be tested this way:

```
sudo apt-get purge shellinabox -y
sudo apt-get install shellinabox
sudo rm /etc/shellinabox/options-enabled/01* -v
sudo dpkg -i ../shellinabox_2.15-1_armhf.deb
find /etc/shellinabox
```

**Comment by KLuka** [comment]
Solved :+1:
