### ISSUE TITLE
Content-Length error from shellinabox.js

### ISSUE THREAD

**Issue by pragatir** [shellinabox/shellinabox#318]
I am getting the following error whenever a POST call is made by shellinabox.

Refused to set unsafe header "Content-Length"
ShellInABox.sendRequest @ ShellInABox.js:4630
(anonymous function) @ ShellInABox.js:4573
setTimeout (async)ShellInABox @ ShellInABox.js:4575
(anonymous function) @ VM9491:1
setTimeout (async)onload @ ?hostname=10.192.124.122:111

Is there any fix for this?

**Comment by KLuka** [comment]
Hi, I think this was fixed in our fork with commit 821ee789c4077942e57d8cef0521e9bb484663f3. What version of shellinabox are you using? You can build the latest version of shellinabox from our repo. Just follow the instructions from README.md.

**Comment by Tushkiz** [comment]
Great, Thank you @KLuka

**Comment by KLuka** [comment]
NP @Tushkiz.

I am closing this down as sloved.
