### ISSUE TITLE
Unix domain support

### ISSUE THREAD

**Issue by rkd77** [shellinabox/shellinabox#319]
nginx allow to proxy_pass to unix domain sockets.
Such a feature would be helpful.

**Comment by KLuka** [comment]
Hi, could you tell us a bit more about this feature and why it would be useful. And some example would be nice too :)

If I understand things correctly this would mean that shellinabox needs to listen and accept connections on unix domain (AF_UNIX). This could be implemented similar as option `--localhost-only` (?).

**Comment by rkd77** [comment]
On hosts where there are more users, everybody can access localhost. Some iptables rules might be added to disallow access to shellinabox, but it is not always possible. AF_UNIX gives a bit better protection.

--unix-socket name:user:group:chmod . For example:
--unix-socket /run/shell.sock:root:root:0660

I consider shellinabox as an alternative to noVNC and let the remote users access it, but not the local ones.

**Comment by KLuka** [comment]
Ok, this feature seams useful and reasonable, thanks for explanation :) I you have time and know-how feel free to issue a PR with a patch, otherwise I will take a look on how to implement this soon...

Example options also seams good, I would just change name. To something like this `--unixdomain-only <path>:<user>:<group>:<chmod>`, so it is similar to `--localhost-only` option.

**Comment by rkd77** [comment]
Here is a fragment of nginx config:
location /auth
{
   root /home/test;
   include snippets/fastcgi-php.conf;
   fastcgi_pass unix:/var/run/php5-fpm.conf;
}

location /vc/
{
   auth_request /auth;
   proxy_pass http://unix:/tmp/tmp.sock;
}

The script in /auth decides whether to let access the terminal or not. Either 200 OK or 403 Forbidden
shellinaboxed might be run with many sessions at once, eg.
shellinaboxed --unixdomain-only=/tmp/tmp.sock:nobody:root:0660 -t -s /vc/1/:user1:group1:/home/user1:/somescript1 -s /vc/2/:user2:group2:/home/user2:/somescript2
etc

/auth gets $_SERVER['REQUEST_URI'] in php and other variables, so it is able to verify access rights to the given terminal.

**Comment by KLuka** [comment]
Thanks for the info @rkd77. I guess that shellinabox can be used in a lot of different ways :)

I will test your solution #320 on Sunday. Did you see my last comment on your commit?

**Comment by KLuka** [comment]
Solution from #320 and commit c6186530bbba790f417a44d008fa26f77f0e77df fixed this issue :+1:

**Comment by rkd77** [comment]
Thanks, one issue left:
unixDomainChmod      = strtol(s, NULL, 0);

This interprets 600 as decimal. strtol(s, NULL, 8); would be better.
600 and 0600 are the same for base 8.

**Comment by KLuka** [comment]
Oh, you are correct. I didn't notice this even when you mentioned in your previous comment... Now I did some research and base 8 is really the way to go :) I will fix this :+1:
