### ISSUE TITLE
need to send ctrl+x o other shortcuts to shellinabox by pressing a custom button

### ISSUE THREAD

**Issue by fsimon21** [shellinabox/shellinabox#322]
hello,
i have a shellinabox session opened in an iframe and, by pressing some buttons, i can send custom commands to the shell.
Now i need to send a ctrl+x and other shortcuts to the shell always by pressing a button, but i don't know how can i do this

thanks for help!

**Comment by KLuka** [comment]
Hello @fsimon21, if you are using examples from `misc/embedded.html`, I think that you can simply do this by sending unicode characters that mimic key shortcuts as commands...

This example is for Ctrl+X, but you can do other charaters like Ctrl+C (\u0003) and so on...

```javascript
iframe.contentWindow.postMessage(JSON.stringify({
	type : "input",
	data : "\u0018" // Ctrl+X unicode
}), "https://192.168.1.150:4200");
```
I think that this should work. Please let me know how it goes...

**Comment by fsimon21** [comment]
hello!

perfect, thanks!! ;-)

**Comment by KLuka** [comment]
Ok, great and thanks for the feedback :+1:
