### ISSUE TITLE
Removal

### ISSUE THREAD

**Issue by tekkbebe** [shellinabox/shellinabox#323]
@KLuka  thanks for working on this.   I git cloned and build a package for Debian Wheezy.  When I purged the package init script and run levels were not removed.

Are you guys close to getting this hosted with the Debian maintainer???

**Comment by KLuka** [comment]
Hello, @tekkbebe and thanks for your support :)

>  I git cloned and build a package for Debian Wheezy. When I purged the package init script and run levels were not removed.

Did you use `purge` or `remove` parameter? Command `apt-get remove shellinabox` doesn't remove the init file. I was always using `apt-get purge shellinabox`, which works as expected. So I didn't run into this problem at least on Ubuntu...

I guess we will have to check the difference between the two commands and fix this if necessary, maybe @a-detiste can help us again :) 

> Are you guys close to getting this hosted with the Debian maintainer???

I am actually in contact with @beewoolie, Debian maintainer for shellinabox package. He promised that he will upload our version to official Debian repository. But he is busy with other stuff so that may take some more time. You can also check this [official bug report](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=785181)...

**Comment by a-detiste** [comment]
I don't see anything special here. `piuparts` test suite didn't complained either.

> /etc/init.d/shellinabox

```shell
# Exit if the package is not installed                                                                                                      
[ -x $DAEMON ] || exit 0
```

**Comment by KLuka** [comment]
Hmm, if @tekkbebe used `remove` command, I also don't see the issues here. Lets wait for more information from him...

Here is the difference between purge and remove commands from `man apt-get`.
```
       remove
           remove is identical to install except that packages are removed instead of installed. Note that removing a package leaves
           its configuration files on the system. If a plus sign is appended to the package name (with no intervening space), the
           identified package will be installed instead of removed.

       purge
           purge is identical to remove except that packages are removed and purged (any configuration files are deleted too).
```
Does anyone know if `/etc/init.d/shellinabox` is considered as configuration file and should not be removed with `remove` command?

**Comment by a-detiste** [comment]
Everything under /etc is considered configuration files.

**Comment by tekkbebe** [comment]
I just checked again.  Thought I purged but I must have dpkg -r.... I usually purge but probably used dpkg -r because I had built the package.  Here is what is left after purge:

/var/lib/shellinabox
/var/lib/shellinabox/certificate-192.168.1.29.pem
/var/lib/shellinabox/.ssh

Are you close to getting this hosted by Debian repos?  Hope so...

I notice when I exit, or disconnect, and then click on the connect button in the middle of the screen it will not reconnect like it did in the past.  Is anyone else experiencing this issue.

Again, thanks for your work on this...

**Comment by a-detiste** [comment]
You're right for `/var/lib/shellinabox` & piuparts can't detect this problem that only happens at runtime.

debian/shellinabox.postrm does this,
which could be written also as `rmdir --ignore-fail-on-non-empty`.

```shell
d=/var/lib/shellinabox
case "$1" in
    purge)
        [ ! -d "$d" ] || rmdir "$d" || true    # deluser can't do this for /var
    ;;
esac
```
Maybe maintainer was thinking, *"these SSL certificates are too much important to be removed; let's remove this folder only if it is empty"*  (= when no one has ever connected to SiaB); or the goal was to make it work with `piuparts`, but not really make it policy-compliant.

On Debian there are two operations: `remove` & `purge`, no `super purge` that purge super-important files not handled by `purge`; so SiaB should be fixed here.

```patch
-        [ ! -d "$d" ] || rmdir "$d" || true    # deluser can't do this for /var
+        rm -rf "$d"
```

For example, even PostgreSQL will delete all it's database cluster on a purge & a purge is never triggered automaticaly by installing some (theorical) conflicting package; so this should be the way to go to make `purge` work as expected.
https://sources.debian.net/src/postgresql-9.4/9.4.4-1/debian/postgresql-9.4.postrm/

**Comment by a-detiste** [comment]
@KLuka 

I'm not fan of a big blind `rm -rf`.

Can you check that this match all the current & previous possible files stored in
`/var/lib/shellinabox`?  

This way, if admin had stored anything else there; `purge` will correctly fail on `rmdir`.

```patch
     purge)
         deluser  --quiet --system shellinabox > /dev/null || true
         delgroup --quiet --system shellinabox > /dev/null || true
-       [ ! -d "$d" ] || rmdir "$d" || true    # deluser can't do this for /var
        rm -rf "/etc/shellinabox/options-enabled"
-       exit 0
+       [ -d "$d" ] || exit 0
+       rm "$d/*.pem"
+       rm "$d/.rnd"
+       rm "$d/.ssh"
+       rmdir "$d"
     ;;
 esac
```

**Comment by KLuka** [comment]
@a-detiste Thanks for your help and explanations :) 

Your patch looks good, but I too have an issue with deleting certificates... Admin might store signed certificate on this directory and it will be deleted on purge... I don't know what is the right thing to do here? Do we have any more ideas?

@tekkbebe 

> Are you close to getting this hosted by Debian repos? Hope so...

I hope so too :) But I don't really know when Marc will have some time... I received last email one month ago where he said he will upload the package. I will ask him again today. I hope he will be able to handle this, or maybe he could let @a-detiste to take over the package...

> I notice when I exit, or disconnect, and then click on the connect button in the middle of the screen it will not reconnect like it did in the past. Is anyone else experiencing this issue.

I don't see this problem with default Debian package and settings... Could you provide some more information on the issue. Like maybe how do you run shellinabox, what browser, maybe some JS console errors etc...

**Comment by KLuka** [comment]
Hello, @tekkbebe new shellianbox release (v2.16) for was uploaded to Debian. Many thanks to @beewoolie and @a-detiste :beers: Please see this [link](https://tracker.debian.org/pkg/shellinabox) for more information...

Regarding your issue about files in `/var/lib/shellinabox`, I have to tell you that this was not changed and files will not be automatically removed. Main reason is that files may be important and it is not wise to remove them on purge... If you need this in your project, I advise you that you use some kind of helper script that removes this files after purge.

Please post more info about your second issue, but I think that you may have a problem on your part. Maybe it has something to do on how you integrated shellinabox to your application...

I will close this issue for now, but if you or someone else has any comments please feel free to post them here.
