### ISSUE TITLE
clear screen before disconnecting

### ISSUE THREAD

**Issue by polytan02** [shellinabox/shellinabox#326]
Hello,

Thanks for all the good work guys ! :)

I think it would be good if the screen would be cleared after the initial ssh connection is closed.

Cheers,

Polytan02

**Comment by KLuka** [comment]
Hello @polytan02, long time no see :)

We can fix this in no time, but I don't know if I like the idea :) When you click on "Connect" button screen is cleared, but before that it is maybe good that output stays on screen.

It could be useful in situations when you get sudden disconnects and you want to copy some data before you try to reconnect and so on...

I don't know if we should change this... What do you think?

**Comment by polytan02** [comment]
I understand your point of view.

Would it be possible then to clear the screen only if the user exits but keep the info if it is an unexpected disconnection ?

We could even have an option somewhere for "clear on exit"

**Comment by BenjiWiebe** [comment]
@polytan02 The easiest way to do that would be for the user to put the command `clear` in their `~/.bash_logout` file.

**Comment by KLuka** [comment]
I agree with @BenjiWiebe on this one. This is a valid solution and we don't need to increase code complexity with detection and additional user options etc... 

Closing as `wontfix`.
