### ISSUE TITLE
Remove build warnings

### ISSUE THREAD

**Issue by beewoolie** [shellinabox/shellinabox#328]
There are several calls to setresuid that should be changed to eliminate the compiler warning:

```
shellinabox/launcher.c:671:7: warning: ignoring return value of ‘setresuid’, declared with attribute warn_unused_result [-Wunused-result]
       setresuid(0, 0, 0);
       ^
```
There is another that may be the fault of our dependencies:
```
libtool: link: ar cru .libs/libhttp.a libhttp/.libs/hashmap.o libhttp/.libs/trie.o libhttp/.libs/httpconnection.o libhttp/.libs/server.o libhttp/.libs/ssl.o libhttp/.libs/url.o
ar: `u' modifier ignored since `D' is the default (see `U')
```

**Comment by KLuka** [comment]
Warnings about calls to `setresuid()` are easy to fix. We just need to add check() macro around them, as they should always be successful or else we will have runtime problems.

For the second issue I need to do some more digging, but I saw some threads that this could be autotools bug (?), but I am not really sure...

**Comment by beewoolie** [comment]
On 7/24/15 9:26 AM, Luka Krajger wrote:
>
> Warnings about calls to |setresuid()| are easy to fix. We just need to 
> add check() macro around them, as they should always be successful or 
> else we will have runtime problems.
>

I figured.  This is a small thing.  IMHO, it's good to close these to 
make sure we're communicating to our users that we know that these 
return values are ignored.  It can be done in the next release.

> For the second issue I need to do some more digging, but I saw some 
> threads that this could be autotools bug (?), but I am not really sure...
>

NP.  Similarly, this is about making sure we're on top of the small 
details.  Not urgent.

**Comment by KLuka** [comment]
Ok, I cleaned up build warnings and I am closing this issue. I also removed `debian/watch` because of lintian warning. I hope that is OK?

**Comment by beewoolie** [comment]
Neat.
