### ISSUE TITLE
build clean should be *clean*

### ISSUE THREAD

**Issue by beewoolie** [shellinabox/shellinabox#329]
There is number of .gitignore entries that can make the source directory difficult to clean.  It's important that debian/rules clean is able to bring the directory tree back to a source clean state and this may not be the case if the autoconf generated files are broken.

Adding `git clean -X` to the `debian/rules` clean target will force the transients to be removed.

Obviously, this could be complicated by the fact that a build is made outside of git.

**Comment by a-detiste** [comment]
I thought `git clean -X` was only needed *once* after the removal of all the auto-generated files from the git indexing.  
I didn't even knew that existed, I did something like `for f in $(cat .gitignore); do rm -rvi "$f"; done`

People clone this repo now or thing like `gbp` or `cowbuilder` shouldn't have any problem at all.

So are changes in `debian/rules`really needed ?

**Comment by beewoolie** [comment]
Not sure.  I stumbled on this because I moved the directory and then the auto* scripts no longer worked.  It's unlikely that this will trip-up most people.

OTOH, I noticed that there are a handful of files in the ignores that remain in the tree after the build clean.  It's desirable to make sure that clean brings the tree back to the 'orig' state.  You can see these files with a `git clean -X -n`.

**Comment by beewoolie** [comment]
I've fixed the debuild clean so that none of the build transients remain after cleanup, but we still get some files in the source archive that shouldn't be there.  I'll take another whack at it.

**Comment by KLuka** [comment]
Nice work :+1:
