### ISSUE TITLE
Please support Forward Secrecy

### ISSUE THREAD

**Issue by marado** [shellinabox/shellinabox#331]
https://en.wikipedia.org/wiki/Forward_secrecy

**Comment by KLuka** [comment]
Hi @marado, thanks for suggestion. I will look this up soon. Do you have any ides how this could be implemented?

**Comment by marado** [comment]
Hi there, unfortunately I am not aquainted with siab's code, I just think this is an important improvement.

Thanks

**Comment by KLuka** [comment]
After brief research I think that we need to add some ciphers to the top of the cipher list where we are setting SSL context. This can be done like this:

```diff
--- a/libhttp/ssl.c
+++ b/libhttp/ssl.c
@@ -617,7 +617,7 @@ static SSL_CTX *sslMakeContext(void) {
 #ifdef SSL_OP_NO_SESSION_RESUMPTION_ON_RENEGOTIATION
   SSL_CTX_set_options(context, SSL_OP_NO_SESSION_RESUMPTION_ON_RENEGOTIATION);
 #endif
-  check(SSL_CTX_set_cipher_list(context, "HIGH:MEDIUM:!aNULL:!MD5"));
+  check(SSL_CTX_set_cipher_list(context, "ECDHE-RSA-AES128-GCM-SHA256:ECDHE-RSA-RC4-SHA:ECDHE-RSA-AES128-SHA:RC4:HIGH:MEDIUM:!aNULL:!MD5"));
   return context;
 }
 #endif
```

I haven't tested this jet, but I think that this also needs better certificate. I will report back soon...

**Comment by a-detiste** [comment]
plain `RC4` before `HIGH` ? :warning:

**Comment by marado** [comment]
We should actually be removing RC4 support...

**Comment by KLuka** [comment]
Opssss, copy/paste mistake. Thanks for warning guys :)

**Comment by marado** [comment]
FYI: I tested a variant of that:

check(SSL_CTX_set_cipher_list(context, "ECDHE-RSA-AES128-GCM-SHA256:ECDHE-RSA-RC4-SHA:ECDHE-RSA-AES128-SHA:HIGH:MEDIUM:!RC4:!aNULL:!MD5"));

SIAB kept working well, both with self-generated certs and provided certs. A test of the result tells that RC4 is no longer available (yay!), everything else keeps working as previously (including the fact that forward secrecy is not working).

**Comment by KLuka** [comment]
I get the same results as you do. I think that certificate has to support
this ciphers...

We need to find a way how to generate a "better" certificate...

**Comment by KLuka** [comment]
Ok, new try :) Forget the certificate stuff that I was talking about... I found a great source of info and code for a patch in this [article](http://vincent.bernat.im/en/blog/2011-ssl-perfect-forward-secrecy.html).

With latest Firefox I managed to get `TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256` connection with default auto generated certificate. This is the quick and dirty patch:

```diff
--- a/libhttp/ssl.c
+++ b/libhttp/ssl.c
@@ -617,7 +617,13 @@ static SSL_CTX *sslMakeContext(void) {
 #ifdef SSL_OP_NO_SESSION_RESUMPTION_ON_RENEGOTIATION
   SSL_CTX_set_options(context, SSL_OP_NO_SESSION_RESUMPTION_ON_RENEGOTIATION);
 #endif
-  check(SSL_CTX_set_cipher_list(context, "HIGH:MEDIUM:!aNULL:!MD5"));
+  check(SSL_CTX_set_cipher_list(context, "ECDHE-RSA-AES128-GCM-SHA256:ECDHE-RSA-RC4-SHA:ECDHE-RSA-AES128-SHA:HIGH:MEDIUM:!RC4:!aNULL:!MD5"));
+
+  EC_KEY *ecdh;
+  check(ecdh = EC_KEY_new_by_curve_name(NID_X9_62_prime256v1));
+  SSL_CTX_set_tmp_ecdh(context,ecdh);
+  EC_KEY_free(ecdh);
+
   return context;
 }
 #endif
```


@marado could you test this? I am also interested how do you test this? Are you using [SSL Labs server test](https://www.ssllabs.com/ssltest/) or something similar?

**Comment by marado** [comment]
Hi there,

Thanks for your time around this.
Yes, this seems to implement PFS, and yes, my tests are being made with ssllabs.

According to it, PFS now only fails when the negotiation is made with the following cyphers:
TLS_RSA_WITH_AES_256_CBC_SHA (0x35)   
TLS_RSA_WITH_AES_128_CBC_SHA (0x2f)   
TLS_RSA_WITH_AES_128_CBC_SHA256 (0x3c)
TLS_RSA_WITH_AES_128_CBC_SHA (0x2f)

**Comment by KLuka** [comment]
Great and thanks for feedback :+1:

I am already working on complete patch that adds more ECDHE-* cyphers so that more browsers will have PFS support. We also need to be careful not to break shellinabox builds with different configuration and for different systems etc...

I also used SSL Labs test (great tool btw) and noticed that shellianbox has some other SSL related issues. I will try to fix them too. I hope that everything gets done and merged to master by the end of this week...

Thanks again :wink:

**Comment by KLuka** [comment]
Changes pulled to master branch. Closing this issue.

**Comment by marado** [comment]
Works great, thanks!
