### ISSUE TITLE
Allow modification of port used in SSH service

### ISSUE THREAD

**Issue by tomberek** [shellinabox/shellinabox#333]
Due to checks at:
https://github.com/shellinabox/shellinabox/blob/master/shellinabox/service.c#L142-L149
one cannot specify the port used by the ssh command by "creative" use of the host name. If we'd like to add another option, or allow something like `123.45.67.89:2222` it should be fairly simple. Let me know if something like this is wanted and I can put it together.

[This](http://unix.stackexchange.com/questions/75668/why-doesnt-the-ssh-command-follow-rfc-on-uri) details why ssh doesn't use user@ip:port syntax. In this case, is there a problem with us detecting the `:` and adding a ` -p PORT` to the host name?

**Comment by KLuka** [comment]
Hello, I don't mind, if we add optional `<port>` parameter for SSH service with `-p` flag. Than the syntax for the command would change like this for example:

```diff
-'SSH' [ : <host> ] 
+'SSH' [ : <host> [ : <port> ] ] 
```

You can check similar discussions in #107 and #84. Also fell free to create PR with a patch and I will examine it soon :wink:

**Comment by KLuka** [comment]
Done with #370.
