### ISSUE TITLE
Add switch to disable utmp writing

### ISSUE THREAD

**Issue by BenjiWiebe** [shellinabox/shellinabox#335]
Please add a switch to disable writing to the utmp file. I might be able to do some work on this, but it will take me a long time to get a feel for the code. If someone else would be able to point me to the right part of the code, or do it themselves, that'd be nice.

**Comment by KLuka** [comment]
Hi @BenjiWiebe, could you explain a bit more why this feature would be useful...

Currently I am a bit busy with other stuff, but I can point you `shellinabox/launcher.c` where you can find the related code. Also I am not sure that we can even disable this logging since we are using PAM sessions for LOGIN service...

**Comment by BenjiWiebe** [comment]
I am using shellinabox for a CMD (not LOGIN) and I don't like the utmp being cluttered by entries from someone briefly connecting to shellinabox. The CMD I am running can in no way be considered a login shell. I have multiple users who log in to my server and I need to be able to easily see them in the utmp file, without having to search through a bunch of shellinabox gibberish.

**Comment by KLuka** [comment]
Ok, that seams reasonable :smile: We could add option like `--disable-utmp-logging`, that can be used, if LOGIN service is not specified...

**Comment by BenjiWiebe** [comment]
I can work on it, but right now I'm just going to comment out all instances of setutxent/endutxent and everything between, since I have to get it disabled today. :)

**Comment by BenjiWiebe** [comment]
I'm afraid I don't understand what role PAM plays in this, though. With all setutxent/endutxent stuff commented out, it no longer writes LOGIN entries, but it does duplicate (?) the last entry in utmp.

**Comment by KLuka** [comment]
Oh, I am sorry I thought that this is related to PAM sessions... Forget about this then :smile:  I am also not sure that I understand what is happening after you commented out setutxent/endutxent stuff. Did you also comment out calls to updwtmpx()?

**Comment by BenjiWiebe** [comment]
Commenting out the updwtmpx() calls seem to fix the wierd issue of the last utmp entry being duplicated. Does that make sense?? Anyways, all that's left is to add a command line switch and change my comments to if's.

**Comment by BenjiWiebe** [comment]
Shall I work on adding this, or just mark it closed? Running SiaB as non-root takes care of the "problem".

**Comment by KLuka** [comment]
> Running SiaB as non-root takes care of the "problem".

That make sense, since non-root users cannot write to this files.

> Shall I work on adding this, or just mark it closed? 

This feature could be useful for other users too, so it would be nice if we implement it :+1: If you wish you can create a patch or I will give it a try when I have some more time...
