### ISSUE TITLE
Child processes not being killed when connection closes

### ISSUE THREAD

**Issue by BenjiWiebe** [shellinabox/shellinabox#337]
When the connection to a SiaB instance closes, the child process is not killed. I verified this with the current Git version, on Fedora 21. I specified the service as a command, "sleep1h.sh", which simply ran 'sleep 1h'. Then I reloaded the page multiple times, and checked the number of 'sleep's that were running. There was one for each time I had reloaded, and there should only have been one.

**Comment by KLuka** [comment]
Yes, this is a known issue (please see #103, #203).

Currently the workarounds are:
* Start shellinabox as non-root user. See 91f6eabe49553bef060b243161b7008a3ae387a8 for more info.
* Use some cleanup cron job, like suggested in #103.

I am closing this as a duplicate. Please let me know how this works for you in #103 .
