### ISSUE TITLE
tetris-bsd doesn't display falling pieces

### ISSUE THREAD

**Issue by a-detiste** [shellinabox/shellinabox#341]
This is a silly bug report, but may also happen in serious software.

Only the score & controls are displayed.

Pieces are displayed as black on black.

```
pi@raspberrypi ~/popcon$ ldd /usr/games/tetris-bsd                                                                                                        
        /usr/lib/arm-linux-gnueabihf/libarmmem.so (0x76ee7000)                                                                                             
        libncurses.so.5 => /lib/arm-linux-gnueabihf/libncurses.so.5 (0x76ea3000)                                                                           
        libtinfo.so.5 => /lib/arm-linux-gnueabihf/libtinfo.so.5 (0x76e74000)                                                                               
        libc.so.6 => /lib/arm-linux-gnueabihf/libc.so.6 (0x76d37000)                                                                                       
        /lib/ld-linux-armhf.so.3 (0x76f0e000)                                                                                                              
        libdl.so.2 => /lib/arm-linux-gnueabihf/libdl.so.2 (0x76d24000)
```

screenshot with expected behaviour:

![tetris-terminal](https://cloud.githubusercontent.com/assets/7994192/9578850/9c7f11f4-4fed-11e5-8aee-dcbe478ff801.png)

**Comment by KLuka** [comment]
Seems lika some terminal escape codes are not detected/handled correctly in `vt100.jspp`...

This could be also related to Debian package bug [788220](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=788220).

**Comment by KLuka** [comment]
Ok, @a-detiste I think I fixed this and it is possible to play tetris with shellinabox :smile: Can you please confirm this solution on your own setup?

**Comment by a-detiste** [comment]
ooh, it's quite a big diff; i'll test it with several other TUI (aptitude, mc, ...) and the other games in `bsd-games`

**Comment by KLuka** [comment]
According to info from @a-detiste this issue is resolved.
