### ISSUE TITLE
(question) is it possible to intercept the answer from the server?

### ISSUE THREAD

**Issue by fsimon21** [shellinabox/shellinabox#345]
hello,
 when i open my terminal i have to send automatically some commands.
To make it possible i need to know when i get the response of the server before send another command

is it possible?

**Comment by KLuka** [comment]
Yes it is possible. From #322 I assume that you are using iframe message passing. Please see this example [file](https://github.com/shellinabox/shellinabox/blob/458cd7aa8f513f41f7eee389fa5ff6a51acea593/misc/embedded.html), and check the `output` type messages.
