### ISSUE TITLE
As Nessus report, SSLv3 is supported by shellinabox 

### ISSUE THREAD

**Issue by YurongWang** [shellinabox/shellinabox#351]
SSLv3 is enabled and the server supports at least one cipher.
Port: 4200 / tcp / www

**Comment by YurongWang** [comment]
Consult the application's documentation to disable SSL 2.0 and 3.0.
Use TLS 1.1 (with approved cipher suites) or higher instead.


Here is the list of medium strength SSL ciphers supported by the remote server :

  Medium Strength Ciphers (>= 56-bit and < 112-bit key)

    TLSv1
      DES-CBC-SHA                  Kx=RSA         Au=RSA      Enc=DES-CBC(56)          Mac=SHA1   

The fields above are :

  {OpenSSL ciphername}
  Kx={key exchange}
  Au={authentication}
  Enc={symmetric encryption method}
  Mac={message authentication code}
  {export flag}

**Comment by KLuka** [comment]
Hello, this issue is already solved with #215. What version are you using? You probably just need to update your package...

**Comment by YurongWang** [comment]
I am using ShellInABox version 2.10 (revision 239).

**Comment by KLuka** [comment]
Yes this is very old version. Please update your package :wink:
