### ISSUE TITLE
impossibile to load custom static file (-f option)

### ISSUE THREAD

**Issue by fsimon21** [shellinabox/shellinabox#352]
Hi,
i'm trying to load a custom page starting from the demo inside the shellinabox dir, but it loads the default page every time. How can i use a custom page ?

I use this command:

sudo ./shellinaboxd --disable-ssl -m '*' -f /demo/demo.html:demo.html 

Thanks!

**Comment by KLuka** [comment]
For me it works as expected. If you get the default page you are probably using wrong URL.

You can access static files from browser like this: `http://<ip address>:<port>/<static file path>`. In your case that would be something like this: `http://<ip address>:4200/demo/demo.html`.
