### ISSUE TITLE
Proxy error 502 error with shellinabox 2.19

### ISSUE THREAD

**Issue by stephdl** [shellinabox/shellinabox#359]
I have had an error with my proxy configuration and shellinabox 2.19

error displayed by the browser

The proxy server received an invalid response from an upstream server. The proxy server could not handle the request GET /shell. Reason: Error reading from remote server 

and in /var/log/httpd/errors

[Sun Jan 10 04:47:29 2016] [error] [client 192.168.12.25] proxy: Error reading from remote server returned by /shell, referer: https://192.168.12.196/shell
[Sun Jan 10 04:47:30 2016] [error] [client 192.168.12.25](20014)Internal error: proxy: error reading status line from remote server 127.0.0.1, referer: https://192.168.12.196/shell

my httpd configuration

  ProxyPass /shell http://127.0.0.1:1870
  ProxyPassReverse /shell http://127.0.0.1:1870

  <Location /shell>
  AuthName "shell"
  order deny,allow
  deny from all
  SSLRequireSSL
  allow from 127.0.0.1 192.168.12.0/255.255.255.0
  </Location>

That was workable with the former version of shellinabox, 2.18 I believe, I solved my Issue if I add to the deamon

/etc/init.d/shellinaboxd

```
 daemon $prog -u $USER -g $GROUP --cert=${CERTDIR} --port=${PORT} --background=$pid $OPTS
```

to

```
 daemon $prog -u $USER -g $GROUP --cert=${CERTDIR} --port=${PORT} --background=$pid --localhost-only --disable-ssl $OPTS
```

It seems that changes to the ssl options has broken my reverse proxy....do you know why ?????

I run shellinabox on centos6 with the epel version.....by the way, now the middle clic to paste is working really well :)

**Comment by stephdl** [comment]
or you can also

--- a/etc/sysconfig/shellinaboxd
+++ b/etc/sysconfig/shellinaboxd
@@ -10,7 +10,7 @@ 
 #OPTS="--disable-ssl-menu -s /:LOGIN"
 #for root login
-OPTS="--no-beep --service=/:SSH"
+OPTS="--no-beep --localhost-only --disable-ssl --service=/:SSH"

**Comment by KLuka** [comment]
Hi, @stephdl I am glad you got it to work and thank you for posting the workaround :+1: 

> It seems that changes to the ssl options has broken my reverse proxy....do you know why ?????

Hm, I am not sure why does this happen with recent changes... Are you using `mod_proxy` with `httpd`? It could be that proxy was using "/plain" fallback to HTTP but I am not sure... 

This issue needs some more investigation, it would be interesting to look at shellinabox debug message or maybe play around with other proxy settings :)

**Comment by stephdl** [comment]
I suppose that I use mod_proxy

httpd -M|grep proxy
Syntax OK
 proxy_module (shared)
 proxy_balancer_module (shared)
 proxy_ftp_module (shared)
 proxy_http_module (shared)
 proxy_ajp_module (shared)
 proxy_connect_module (shared)

I will take time to look after the debug outputs. For me the '--disable-ssl ' is not an issue because I do elsewhere a https redirection when the communication is started on the port 80.

**Comment by mckaygerhard** [comment]
are the ssl cert of apache same at the shellinabox? i have similar problem with an older version of shellinabox, the miscbehavior in ssl certf was the issue and i never could use with bth ssl enabled in reverse proxy

**Comment by mvanholsteijn** [comment]
I have the same problem with 2.19.  An ELB is doing the SSL offloading and the executable crashes with a segmentation violation (502 on the client).

**Comment by KLuka** [comment]
Hi @mvanholsteijn, can you get it to work, if you use `--disable-ssl` for shellinabox? Could you also provide your proxy settings.

**Comment by mckaygerhard** [comment]
@KLuka of course u can get work disabling own ssl, but then relies on the ssl of the server and the port opened must be blocket by a firewall of something..

that! confuses the manpower that have to try to setup to multiple domains or not have good documentation or experience in this kind of software not very commonly

maybe must be a detection that if clients comes from a url that its reverse proxy not used the own ssl build in, and if client comes using the port use the certificate..  
this behabior are in some ambigous due always incommin sill use the port (ex 4200) but must be a origin client request that can be obtained to resolve that!

**Comment by mvanholsteijn** [comment]
The error was caused by the peer change check on the session and the http
requests are forwarded by different elb instances.

I added a --disable-peer-check option to address this

Cheers, Mark

**Comment by mvanholsteijn** [comment]
See my pull request :-)

**Comment by mckaygerhard** [comment]
@mvanholsteijn the responses by mail something cut's part of the message, the previous message was cutted in the most important part..

addiding ` --disable-peer-check ` will be able to not use the ` --disable-ssl` ?

now reviewing the pull to we hope that now can use as expected..

**Comment by KLuka** [comment]
@mvanholsteijn I think that you will still need to use `--disable-ssl` option. I don't know the specifics of your setup, but @mvanholsteijn was having problems with AWS Elastic Load Balancer.

>  the port opened must be blocket by a firewall of something..

You can use `--localhost-only` option, if proxy is running on same server. This will block direct access to port 4200 from other machines. Access will be allowed only from local proxy.

I hope that helps. If you need more info please describe your setup and we will see what can be done...

**Comment by mckaygerhard** [comment]
PLease this important setup information must be added to help/documentation, the behavior explained by @KLuka are right for most secured env!

and if still must be used --disable-ssl this pull request its non.sense the idea its to not need the --disable-ssl option and allow both certificates just like multi-domains (ex google domain services)

**Comment by mvanholsteijn** [comment]
@KLuka the --localhost-only option will not work in my situation as the shellinabox is runnning in a Docker container. When it is listening on localhost only, I cannot reach it from outside.. 

My setup looks as follows: 

```
Browser -> ELB (2 or more) ->  NGiNX (2 or more) ->  Shellinabox Docker Container
```

**Comment by mckaygerhard** [comment]
un in u'r situation @mvanholsteijn the docker conatiner does not follow the standars of the libs available in the main os, so its a special situation aparts of the xpected behabior..

in the situation of me and @KLuka i assume we used the software provides by os.. i currently testing and for now its working, no i'll test with 2 certificates in cascade in differents domain but running shellinabox in same host, then i'll reply here feedback

**Comment by Pupo1** [comment]
Hello everyone, I have the same error 

> "Proxy Error
> 
> The proxy server received an invalid response from an upstream server.
> The proxy server could not handle the request GET /server.
> 
> Reason: Error reading from remote server"

 and having spent my evenings for a week or so trying to solve this issue, I'm giving up now. Could someone please help me? I don't know where to ask elsewhere. - My knowledge to servers and proxies is quite limited and I don't understand @stephdl's solution. I don't know how to make/employ a patch.

- I have a normal server configuration, just a usual apache server on the internet.
my /etc/default/shellinabox contains:
`SHELLINABOX_DAEMON_START=1
SHELLINABOX_PORT=8001
# SHELLINABOX_ARGS="--no-beep -s /:SSH:<my server ip here, did not work either> --localhost only --disable-peer-check"
SHELLINABOX_ARGS="--no-beep --localhost only"
`
my /etc/apache2/sites-available/default-ssl.conf:
```
<IfModule mod_ssl.c>
	<VirtualHost _default_:443>
           (much blah blah here)
	</VirtualHost>
<Location /server>
 ProxyPass http://<my server's ip here. just writing //localhost: does not help.>:8001/
</Location>
</IfModule>
```
I also added the following section to my /etc/apache2/mods-available/proxy.conf:
```
  <Location /shell>
            ProxyPass http://localhost:8001/
            Order allow,deny
            Allow from all
        </Location>

```
Nothing helps. However, I _am_ able to start my shellinabox navigating to 
https://<server ip here>:8001
But I need a reverse proxy because when the computer at my workplace sees the ":8001", Sophos firewall will tell me "service not allowed" and blocks it.

**Comment by Pupo1** [comment]
Okay, I solved my problem - however, I changed so many things, that I am not sure what actually solved the problem.
