### ISSUE TITLE
Support (ignore) VTE OSC6 and OSC7 escape sequences

### ISSUE THREAD

**Issue by jogc** [shellinabox/shellinabox#360]
On at least Ubuntu 14.04 /etc/profile.d/vte.sh makes bash send a special escape sequence containing the current working directory in the form av a file:// URI before every prompt if bash was started with the -l option. Since shellinabox doesn't recognize it it gets displayed and it looks ugly.

**Comment by jogc** [comment]
[shellinabox.diff.txt](https://github.com/shellinabox/shellinabox/files/88257/shellinabox.diff.txt)

**Comment by KLuka** [comment]
I managed to reproduce this issue with something like this:

```
luka@ubuntu:~$ exportVTE_VERSION=4000
luka@ubuntu:~$ source /etc/profile.d/vte.sh
;file://ubuntu/home/lukaluka@ubuntu:~$
;file://ubuntu/home/lukaluka@ubuntu:~$
```

So, thank you for the patch I will try it out soon, or you can also create PR, if you have time :+1:
