### ISSUE TITLE
building with MUSL library for OpenWRT

### ISSUE THREAD

**Issue by artynet** [shellinabox/shellinabox#361]
this time the issue is similar to the previous one here : https://github.com/shellinabox/shellinabox/issues/330. The SDK is the one of the OpenWRT embedded system but now relying on the **MUSL** c embedded library which includes the **utmp.h** and **utmpx.h** headers. However, I get this pointer error :
```
mips-openwrt-linux-musl-gcc -DHAVE_CONFIG_H -I.   -I/home/arturo/temp/openwrt-arty/staging_dir/target-mips_34kc_musl-1.1.12/usr/include -I/home/arturo/temp/openwrt-arty/staging_dir/target-mips_34kc_musl-1.1.12/include -I/home/arturo/temp/openwrt-arty/staging_dir/toolchain-mips_34kc_gcc-5.2.0_musl-1.1.12/usr/include -I/home/arturo/temp/openwrt-arty/staging_dir/toolchain-mips_34kc_gcc-5.2.0_musl-1.1.12/include/fortify -I/home/arturo/temp/openwrt-arty/staging_dir/toolchain-mips_34kc_gcc-5.2.0_musl-1.1.12/include  -g -std=gnu99 -Wall -Os -pipe -mno-branch-likely -mips32r2 -mtune=34kc -fno-caller-saves -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -msoft-float -iremap /home/arturo/temp/openwrt-arty/build_dir/target-mips_34kc_musl-1.1.12/shellinabox-2.20:shellinabox-2.20  -MT shellinabox/launcher.o -MD -MP -MF $depbase.Tpo -c -o shellinabox/launcher.o shellinabox/launcher.c &&\
        mv -f $depbase.Tpo $depbase.Po
shellinabox/launcher.c: In function 'childProcess':
shellinabox/launcher.c:1576:41: error: invalid type argument of '->' (have 'struct utmpx')
     struct utmpx utmpx            = utmp->utmpx;
                                         ^
shellinabox/launcher.c:1585:14: error: invalid type argument of '->' (have 'struct utmpx')
     if (!utmp->useLogin) {
              ^
make[4]: *** [shellinabox/launcher.o] Error 1
make[4]: Leaving directory `/home/arturo/temp/openwrt-arty/build_dir/target-mips_34kc_musl-1.1.12/shellinabox-2.20'
make[3]: *** [all] Error 2
make[3]: Leaving directory `/home/arturo/temp/openwrt-arty/build_dir/target-mips_34kc_musl-1.1.12/shellinabox-2.20'
make[2]: *** [/home/arturo/temp/openwrt-arty/build_dir/target-mips_34kc_musl-1.1.12/shellinabox-2.20/.built] Error 2
make[2]: Leaving directory `/home/arturo/temp/openwrt-arty/package/linino/shellinabox'
make[1]: *** [package/linino/shellinabox/compile] Error 2
make[1]: Leaving directory `/home/arturo/temp/openwrt-arty'
make: *** [package/shellinabox/compile] Error 2
```
any thought about this one ? It seems really strange to me this pointer redirection....please let me know...

**Comment by artynet** [comment]
Hello @KLuka, did you take a look at this one ? any thoughts on that ?

**Comment by KLuka** [comment]
Hi @artynet, sorry I didn't have a chance to take a closer look at this issue...

What did you already tried? Can you maybe provide some info on how would I be able to replicate this?

**Comment by artynet** [comment]
Hello @KLuka, I just download the OpenWRT **trunk** and after making the preliminary steps, I simply launch the build. Here's the typical makefile used for OpenWRT :

https://github.com/artynet/openwrt/blob/gcc5-06/package/linino/shellinabox/Makefile

It seems strange to me since the build with the SDK relying on **uClibc** worked fine. However, I managed to solve the first part of the build error with this simple patch

```patch
--- a/shellianbox/launcher      2016-03-17 15:47:52.472700940 +0100
+++ b/shellinabox/launcher.c    2016-03-17 16:04:00.091405134 +0100
@@ -1574,7 +1574,7 @@
 #ifdef HAVE_UTMPX_H
   if (enableUtmpLogging) {
     setutxent();
-    struct utmpx utmpx            = utmp->utmpx;
+    struct utmpx utmpx;
     if (service->useLogin || service->authUser) {
       utmpx.ut_type               = LOGIN_PROCESS;
       memset(utmpx.ut_host, 0, sizeof(utmpx.ut_host));
@@ -1583,7 +1583,7 @@
     endutxent();
```
the build crashes anyway as you see at the same point :

```
shellinabox/launcher.c: In function 'childProcess':
shellinabox/launcher.c:1586:14: error: invalid type argument of '->' (have 'struct utmpx')
     if (!utmp->useLogin) {
              ^
make[4]: *** [shellinabox/launcher.o] Error 1
make[4]: Leaving directory `/home/arturo/temp/openwrt-arty/build_dir/target-mips_34kc_musl-1.1.14/shellinabox-2.20'
make[3]: *** [all] Error 2
make[3]: Leaving directory `/home/arturo/temp/openwrt-arty/build_dir/target-mips_34kc_musl-1.1.14/shellinabox-2.20'
make[2]: *** [/home/arturo/temp/openwrt-arty/build_dir/target-mips_34kc_musl-1.1.14/shellinabox-2.20/.built] Error 2
make[2]: Leaving directory `/home/arturo/temp/openwrt-arty/package/linino/shellinabox'
make[1]: *** [package/linino/shellinabox/compile] Error 2
make[1]: Leaving directory `/home/arturo/temp/openwrt-arty'
make: *** [package/shellinabox/compile] Error 2
```
That's what I have been able to do until now....

**Comment by KLuka** [comment]
Hm, could you paste lines [L1513-L1515](https://github.com/shellinabox/shellinabox/blob/master/shellinabox/launcher.c#L1513-L1515) from your working copy. It looks like `utmp` is not a pointer in your `childProcess` function???

**Comment by artynet** [comment]
the latest working copy is your latest commit of the source code. No big deal apart from the previous UTMP/UTMPX check patch you made time ago.....the fact is the code build when using **uClibc** and crashes when building with **musl**...

**Comment by artynet** [comment]
it turns out that just removing the `utmp.h` import did the trick : 

```patch
--- a/shellinabox/launcher.c    2016-04-30 18:29:20.067289912 +0200
+++ b/shellinabox/launcher.c    2016-04-30 18:49:36.479015732 +0200
@@ -85,10 +85,6 @@
 #include <util.h>
 #endif

-#ifdef HAVE_UTMP_H
-#include <utmp.h>
-#endif
-
 #ifdef HAVE_UTMPX_H
 #include <utmpx.h>
 #endif
```
can you double-check if the solution might be correct or not ?

Best, Arturo

**Comment by KLuka** [comment]
Ok, I am sorry but I still didn't setup my environment to test this... I am glad that you manage to figure it out and posted the info here, for others to see :+1:

I found some additional info on link bellow but I am not sure how can we use this to create a proper patch... You are more than welcome to try it out :)

> ... but generally you should disable utmp support on musl-based systems anyway. musl's utmp is intentionally stubbed out to do nothing, and some programs print spurious runtime warnings/errors too if it's enabled ...

Source: http://comments.gmane.org/gmane.linux.lib.musl.general/9215

**Comment by xdtianyu** [comment]
Hello @artynet , I'm facing the same problem, I made the follow change and every thing works fine.

```diff
diff --git a/shellinabox/launcher.c b/shellinabox/launcher.c
index 2bac171..2df1f3f 100644
--- a/shellinabox/launcher.c
+++ b/shellinabox/launcher.c
@@ -81,6 +81,10 @@
 #include <sys/uio.h>
 #endif

+#ifndef TTYDEF_IFLAG
+#include <sys/ttydefaults.h>
+#endif
+
 #ifdef HAVE_UTIL_H
 #include <util.h>
 #endif
@@ -90,7 +94,8 @@
 #endif

 #ifdef HAVE_UTMPX_H
-#include <utmpx.h>
+//#include <utmpx.h>
+#undef HAVE_UTMPX_H
 #endif

 #if defined(HAVE_SECURITY_PAM_APPL_H)
```
Here is  my main build steps may help others:

**1\. Export environment**
```
PATH=$PATH:$HOME/OpenWrt-SDK-bcm53xx_gcc-5.3.0_musl-1.1.14_eabi.Linux-x86_64/staging_dir/toolchain-arm_cortex-a9_gcc-5.3.0_musl-1.1.14_eabi/bin
export PATH
STAGING_DIRPATH=$HOME/OpenWrt-SDK-bcm53xx_gcc-5.3.0_musl-1.1.14_eabi.Linux-x86_64/staging_dir/toolchain-arm_cortex-a9_gcc-5.3.0_musl-1.1.14_eabi
export STAGING_DIRPATH
STAGING_DIR=$HOME/OpenWrt-SDK-bcm53xx_gcc-5.3.0_musl-1.1.14_eabi.Linux-x86_64/staging_dir/toolchain-arm_cortex-a9_gcc-5.3.0_musl-1.1.14_eabi
export STAGING_DIR

CFLAGS=-I$HOME/OpenWrt-SDK-bcm53xx_gcc-5.3.0_musl-1.1.14_eabi.Linux-x86_64/staging_dir/target-arm_cortex-a9_musl-1.1.14_eabi/usr/include
LDFLAGS=-L$HOME/OpenWrt-SDK-bcm53xx_gcc-5.3.0_musl-1.1.14_eabi.Linux-x86_64/staging_dir/target-arm_cortex-a9_musl-1.1.14_eabi/usr/lib

export CFLAGS
export LDFLAGS
```
The sdk is from [openwrt snapshots trunk](https://downloads.openwrt.org/snapshots/trunk/)

**2\. Install cross compile dependencies**

The build need `libpam` and `libzip` in `target-arm_cortex-a9_musl-1.1.14_eabi/usr/include`, so I build `nginx` and `openssh` first which need these dependencies too,  for a quick workaround.

```
./scripts/feeds update
./scripts/feeds install nginx openssh-server-pam
make package/feeds/packages/nginx/compile V=s
make package/feeds/packages/openssh/compile V=s
```

**3\. Make shellinabox**

```
autoreconf -i
./configure
make CC=arm-openwrt-linux-muslgnueabi-gcc LD=arm-openwrt-linux-muslgnueabi-ld
```

**Comment by artynet** [comment]
hello @xdtianyu, please consider using this small addition to your patch if using musl 1.15.0 (as in LEDE for instance)

```patch
--- a/shellinabox/launcher.c    2016-08-01 16:15:25.018260726 +0200
+++ b/shellinabox/launcher.c    2016-08-01 16:16:50.271765498 +0200
@@ -81,6 +81,10 @@
 #include <sys/uio.h>
 #endif

+#ifndef TTYDEF_IFLAG
+#include <sys/ttydefaults.h>
+#endif
+
 #ifdef HAVE_UTIL_H
 #include <util.h>
 #endif
@@ -90,9 +94,12 @@
 #endif

 #ifdef HAVE_UTMPX_H
-#include <utmpx.h>
+//#include <utmpx.h>
+#undef HAVE_UTMPX_H
 #endif

+#define HAVE_PTSNAME_R 1
+
 #if defined(HAVE_SECURITY_PAM_APPL_H)
 #include <security/pam_appl.h>
```

since **ptsname_r** is already defined in musl's stdlib.h

    Best,Arturo

**Comment by KLuka** [comment]
Hi all, I am working on this issue and I came to solution that would allow user to configure build without utmp. This would enable shellinabox to be built against musl lib, you woud just need to run something like `./configure --disable-utmp`.

Please let me know what do you think?

**Comment by KLuka** [comment]
Ok, I committed the patch and by my tests shellinabox should compile with musl libc. Can someone else verify this... Please checkout latest master and run:

```
autoreconf -iv
./configure --disable-utmp 
make
```

**Comment by xdtianyu** [comment]
@KLuka I have tested with `OpenWrt-SDK-bcm53xx_gcc-5.3.0_musl-1.1.15_eabi.Linux-x86_64` in a clean build, works great, thanks.

**Comment by KLuka** [comment]
Thanks :wink:

**Comment by artynet** [comment]
@KLuka Tested with `toolchain-mips_24kc_gcc-5.4.0_musl-1.1.15` and it works fine ! thank you !
