### ISSUE TITLE
shellinabox cannot run behind AWS Elastic Load Balancer (ELB) - Peername changed

### ISSUE THREAD

**Issue by mvanholsteijn** [shellinabox/shellinabox#364]
When you run shellinabox behind a AWS ELB which does the SSL offloading for you, shellinabox closes the session because subsequent HTTP requests are issued by different ELB instances..

The second request closes the connection with the error: 
   Peername changed from ... to ....

It would be nice if we could disable this peer check...

```
[http] Compressed response from 2307 to 1995
[http] ip-10-0-4-187.eu-central-1.compute.internal - - [25/Feb/2016:22:35:44 +0000] "GET /favicon.ico HTTP/1.0" 200 2088
[http] Closing connection to ip-10-0-4-187.eu-central-1.compute.internal:37535
[http] Accepted connection from ip-10-0-3-142.eu-central-1.compute.internal:58847
[http] Handling "POST" "/?"
[server] Peername changed from ip-10-0-4-187.eu-central-1.compute.internal to ip-10-0-3-142.eu-central-1.compute.internal
```

**Comment by KLuka** [comment]
Thanks for identifying the issue and implementing the fix :+1: I am closing this issue since your change has been merged in master. If you find any more problems please let me know and we can reopen it ;)
