### ISSUE TITLE
shellinabox segfaults

### ISSUE THREAD

**Issue by marado** [shellinabox/shellinabox#381]
Hi there,

After I upgraded shellinabox, I stopped having four stable instances of SIAB constantly running, to have regular crashes: in two days (more or less) I see at least one of them crashing. The observed result is that the process is no longer running. I didn't try to debug the issue, but, knowing it was a regression, I started bissecting the code.

Turns out the culprit is the commit: d74e60b6a76b8f577366586e0c485986aa0e5874 . While this isn't deterministic, I really am unable to have SIAB running for a long time, but if I simply revert that commit, I get a stable process (running for 19 days without a problem, at this moment).

Once, I happened to have a shell opened on the server when one of the processes crashed, this was what I saw: 
```
[server] Peername changed from 66.249.79.160 to 66.249.79.167
bash: line 14: 28111 Segmentation fault      (core dumped) shellinaboxd --css=/[path-here].css -p 443 -s '[stuff-here]'
```
I am not sure if this is enough information to help you debug the situation...

**Comment by KLuka** [comment]
Hi, thanks for great report. I was able to reproduce and solve the issue.  :+1:

Please check the latest commit.

**Comment by marado** [comment]
Well, I'm sorry I didn't have more time to actually find the problem and submit a patch, but thanks for fix!
