### ISSUE TITLE
Bug#828542: FTBFS with openssl 1.1.0

### ISSUE THREAD

**Issue by a-detiste** [shellinabox/shellinabox#384]
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=828542

---

Hi,

OpenSSL 1.1.0 is about to released.  During a rebuild of all packages using
OpenSSL this package fail to build.  A log of that build can be found at:
https://breakpoint.cc/openssl-1.1-rebuild-2016-05-29/Attempted/shellinabox_2.19_amd64-20160529-1535

On https://wiki.openssl.org/index.php/1.1_API_Changes you can see various of the
reasons why it might fail.  There are also updated man pages at
https://www.openssl.org/docs/manmaster/ that should contain useful information.

There is a libssl-dev package available in experimental that contains a recent
snapshot, I suggest you try building against that to see if everything works.

If you have problems making things work, feel free to contact us.

Kurt

**Comment by KLuka** [comment]
Thanks for reporting I will investigate soon as possible. Help and patches are always welcome :)

**Comment by KLuka** [comment]
Problem for building against openssl 1.1.0 is direct usage of `BIO` struct members in function `sslFreeHndl()`. From the comments in that function I assume that this was done as a workaround for openssl bug described bellow...

> In OpenSSL versions before 1.0.0 the BIO_pop() call was handled incorrectly, the I/O BIO reference count was incorrectly incremented (instead of decremented) and dissociated with the SSL BIO even if the SSL  BIO was not explicitly being popped (e.g. a pop higher up the chain). Applications which included workarounds for this bug (e.g. freeing BIOs more than once) should be modified to handle this fix or they may free up an already freed BIO.
Source: https://www.openssl.org/docs/manmaster/crypto/BIO_f_ssl.html

Comment in the function:

> OpenSSL does not always correctly perform reference counting for stacked BIOs. This is particularly a problem if an SSL connection has two different BIOs for the read and the write end, with one being a stacked derivative of the other. Unfortunately, this is exactly the scenario that we set up. As a work-around, we un-stack the BIOs prior to freeing the SSL connection.

I think that correct solution for build problem is to disable "workaround code" for openssl >= 1.1.0 (just to be on the safe side). We trust that `SSL_free()` will correctly handle freeing its underlying resources (BIOs) from now on...

**Comment by KLuka** [comment]
Closing this issue since debian package can be successfully build from latest master. I think that new version can be uploaded.

I also opened #393 for general compatibility problems. I will work on that soon.

/cc @beewoolie
