### ISSUE TITLE
buildroot - shellinabox build error

### ISSUE THREAD

**Issue by osingla** [shellinabox/shellinabox#388]
Hi,

I have submitted a patch to the buildroot community to add shellinabox. With the latest buildroot, there are some issue to build it:
http://autobuild.buildroot.net/results/184/1847cab964957da3c9bf4911a5ad3602b3c82431/

Not sure why it would not build in this particular case...

Olivier

**Comment by KLuka** [comment]
Hi it looks like there are some missing headers. Can you try this patch:

```
diff --git a/shellinabox/launcher.c b/shellinabox/launcher.c
index 2bac171..ba54b36 100644
--- a/shellinabox/launcher.c
+++ b/shellinabox/launcher.c
@@ -63,6 +63,7 @@
 #include <sys/socket.h>
 #include <sys/stat.h>
 #include <sys/time.h>
+#include <sys/ttydefaults.h>
 #include <sys/types.h>
 #include <sys/wait.h>
 #include <sys/utsname.h>
```

**Comment by artynet** [comment]
Hello @osingla, please consider using this patch here :

https://github.com/shellinabox/shellinabox/issues/361#issuecomment-236594594

made by @xdtianyu with a simple addition of mine. Best, Arturo.

**Comment by KLuka** [comment]
Resolved. Please see #361.
