### ISSUE TITLE
No new release tag?

### ISSUE THREAD

**Issue by danger89** [shellinabox/shellinabox#396]
I think it's a good idea to tag a new version at some point. The 'latest' version is from 2015, it's almost 2017 now....

In fact, I see a lot of commits in the past years and months. Please, create a new stable tag.
It makes it also very clear that we finally have a new version after your fork :+1: .

Thanks!
- Melroy

**Comment by KLuka** [comment]
Hi, new release was made. Please see this link: https://github.com/shellinabox/shellinabox/releases/tag/v2.20
