### ISSUE TITLE
What I did with your work, EG : Shellinabox on NethServer7

### ISSUE THREAD

**Issue by stephdl** [shellinabox/shellinabox#398]
Hi all

Not a bug, or an Issue, Just some rewards you deserve to have for your hard work :)

This what I did with some proxypass and apache authentication (if wanted/needed) to display shellinabox in the server-manager of NethServer.

![capture d ecran de 2016-11-12 09-36-26](https://cloud.githubusercontent.com/assets/3164851/20236701/19a304e6-a8bd-11e6-8023-dab7b2715988.png)
![capture d ecran de 2016-11-12 09-36-56](https://cloud.githubusercontent.com/assets/3164851/20236700/19a27fda-a8bd-11e6-9702-41c2b5c41a86.png)

Keep the good work !

**Comment by uudruid74** [comment]
Some people are moving to xterm.js which I feel is less mature although it uses newer technologies, is slightly faster (I think it uses websockets, not sure), and has better mouse support in some instances (not all).   There is also my shellinabox fork (lots of changes) which I hope to sync up with this one eventually so all major shellinabox forks are either abandoned or up to date :smile:   I'm kinda hinting to others that they should close down abandoned forks.  It may be a couple weeks before I can get us synced up, but be sure to check back as I think there will be a lot of new functionality soon and it will be worth an upgrade.
