### ISSUE TITLE
How to set up SIAB for a root URL (e.g., https://example.com)?

### ISSUE THREAD

**Issue by zoof** [shellinabox/shellinabox#409]
My first thought was to create an empty Apache site with the code:

    <Location />
        ProxyPass http://127.0.0.1:4200
        Allow from 127.0.0.1
    </Location>

but this does not appear to be working.  It goes to SIAB but when it starts looking for various resources, it is unable to find them.  E.g., the error log:

    [Fri Mar 17 08:45:45.141388 2017] [proxy:error] [pid 25526] [client 127.0.0.1:38239] AH00898: DNS lookup failure for: 127.0.0.1:4200shellinabox.js returned by /ShellInABox.js, referer: https://example.com/
    [Fri Mar 17 08:45:45.142969 2017] [proxy:error] [pid 25527] [client 127.0.0.1:38235] AH00898: DNS lookup failure for: 127.0.0.1:4200styles.css returned by /styles.css, referer: https://example.com/
    [Fri Mar 17 08:45:45.153817 2017] [proxy:error] [pid 25527] [client 127.0.0.1:38235] AH00898: DNS lookup failure for: 127.0.0.1:4200shellinabox.js returned by /ShellInABox.js, referer: https://example.com/
    [Fri Mar 17 08:45:45.231499 2017] [proxy:error] [pid 25527] [client 127.0.0.1:38235] AH00898: DNS lookup failure for: 127.0.0.1:4200favicon.ico returned by /favicon.ico, referer: https://example.com/

Perhaps this is not the right way to do this?

**Comment by uudruid74** [comment]
Look at the logs and you'll see the issue.  Try adding another slash at the end of your proxypass statement

**Comment by zoof** [comment]
Many thanks!  That did it.
