### ISSUE TITLE
Server returns empty responce

### ISSUE THREAD

**Issue by CaptiveCreeper** [shellinabox/shellinabox#416]
When I start the server it shows no errors but when I go to the url of the page it gives a "ERR_EMPTY_RESPONSE". This is on localhost as well as other computers on the network. I have not changed any of the settings except trying to change the port a few times to fix it. Thanks in advance for the help.

**Comment by xmduhan** [comment]
Try use https instead, for example: https//:localhost:4200

**Comment by CaptiveCreeper** [comment]
That worked thanks. Why is it always the simple things...

**Comment by marado** [comment]
This is related to #371 .

**Comment by maravento** [comment]
Shellinabox began to fail a few days ago
Ubuntu 18.04.1 LTS x64, testing in Chrome v 70.0.3538.77 (Build oficial) (64 bits) and Firefox Quantum 63.
![fail](https://user-images.githubusercontent.com/14880802/48271314-0e912800-e40a-11e8-8a0d-377eb156bd7e.png)
**Note:** I have changed the default port 4200 to 4242 to avoid conflicts with [SnapWeb](https://github.com/snapcore/snapweb) (use 4200 and 4201)
