### ISSUE TITLE
Failed to generate self-signed certificate "certificate.pem"

### ISSUE THREAD

**Issue by blub4747** [shellinabox/shellinabox#419]
Hi guys,

I just built shellinabox and when I wanted to run it for the first time  I ended up with a error msg notifying me about the failed attempt to generate a  self-signed certificat.
However I did install all the nessary depencies including all ssl relevant ones.

Could someone please to track down the reasson for this error.
Please let me know which log files are required.

thx,blub4747

**Comment by qbeukes** [comment]
which command line did you use?

**Comment by blub4747** [comment]
I ran ./configure - without any errors
make - gave me the following errors - 

`Makefile:695:`
` recipe for target 'shellinaboxd' failed
`make[1]: *** [shellinaboxd] Error 1
`make[1]: Leaving directory '/home/blub/Downloads/shellinabox'
`Makefile:529: recipe for target 'all' failed
`make: *** [all] Error 2

make install - 
collect2: error: ld returned 1 exit status
Makefile:695: recipe for target 'shellinaboxd' failed
make[1]: *** [shellinaboxd] Error 1
make[1]: Leaving directory '/home/blub/Downloads/shellinabox'
Makefile:1055: recipe for target 'install' failed
make: *** [install] Error
