### ISSUE TITLE
Check failed at shellinabox/launcher.c:721 in closeAllFds(): nullFd > 2

### ISSUE THREAD

**Issue by kevin335200** [shellinabox/shellinabox#444]
Running on Netgear R7000

**Comment by 1kevin335200** [comment]
Shellinaboxd process will close when i try to connect port 4200.
I can see a cursor and nothing else.

**Comment by rprasanth** [comment]
are you trying the command as a root user?
```
# shellinaboxd -t -d
```
If so, Try to pass 
```
# shellinaboxd -t -d -u root -g root
```

**Comment by kevin335200** [comment]
Since I no longer have access to the device, I will close this issue, but thanks for the reply!

**Comment by anysoft** [comment]
/jffs/.koolshare/scripts/shellinabox_config.sh 

/koolshare/shellinabox/shellinaboxd  -u root--css=/koolshare/shellinabox
/white-on-black.css -b/koolshare/shellinabox/shellinaboxd  -u lipu --css=/koolshare/shellinabox


root is you username

> Since I no longer have access to the device, I will close this issue, but thanks for the reply!

/jffs/.koolshare/scripts/shellinabox_config.sh 

/koolshare/shellinabox/shellinaboxd  -u root--css=/koolshare/shellinabox
/white-on-black.css -b/koolshare/shellinabox/shellinaboxd  -u lipu --css=/koolshare/shellinabox


root is you username
