### ISSUE TITLE
Empty reply from server

### ISSUE THREAD

**Issue by ii64** [shellinabox/shellinabox#452]
![image](https://user-images.githubusercontent.com/26342994/50443704-23346b80-0937-11e9-85d1-bc967ed30d34.png)
![image](https://user-images.githubusercontent.com/26342994/50443836-9fc74a00-0937-11e9-8e5c-7c1b193ec16b.png)
Anyone know why the server is not responding any request?
The service is already running, it worked before we restart the server. 
Current flow: CloudFlare -> NGINX -> ShellInABox (:6743)
Image: Ubuntu 18.04.1 LTS

**Comment by nigels-com** [comment]
Try `https://localhost:6743`

**Comment by anysz** [comment]
> `Empty reply from server`

I have no idea tbh, server is up, tcp already listening

**Comment by binary-person** [comment]
Try to look for what port your shellinaboxd is running at, under config file `/etc/default/shellinabox`

**Comment by ii64** [comment]
Fixed, Thanks.
