### ISSUE TITLE
emacs refresh is slow through shellinabox

### ISSUE THREAD

**Issue by KLuka** [shellinabox/shellinabox#52]
_From [riccardi...@gmail.com](https://code.google.com/u/110092272103816952673/) on February 16, 2010 20:13:43_

First, thank you for your easy to setup & use web shell.

So here is the issue: What steps will reproduce the problem? 1. login
2. start emacs -Q
3. wait for lines to appear What is the expected output? What do you see instead? Each line of the interface takes 1 to 2 seconds to display, instead of the normal speed of refresh 
(several thousands lines per second when not in emacs). What version of the product are you using? On what operating system? I'm using shellinabox_2.10-1_amd64.deb on debian testing.

_Original issue: http://code.google.com/p/shellinabox/issues/detail?id=52_

**Comment by KLuka** [comment]
_From [elibarzi](https://code.google.com/u/elibarzi/) on March 01, 2010 00:56:17_

I have seen the same behavior.  Running with --debug, it looks like there is a
one-second query per line, which happens every time Emacs is trying to refresh
the screen.  Another weird thing that I've noticed is that the rate is *exactly*
one line per second -- so there might be some 1s delay somewhere in the code...

**Comment by KLuka** [comment]
_From [zod...@gmail.com](https://code.google.com/u/109388341641331418132/) on October 02, 2010 16:55:56_

Can you check again if the problem still exists. I just fixed a bug that might be related to your problem (which incidentally, I have been unable to reproduce myself).

**Comment by KLuka** [comment]
_From [elibarzi](https://code.google.com/u/elibarzi/) on October 02, 2010 21:08:52_

I re-tried it using the code from svn, and it's still slow.

I don't remember exactly the details last time, but one thing that I tried now is
running Emacs with my default environment, which uses a white-on-black color scheme.
(The colors work fine, only the delays are an issue).  Then I tried with a -q, and
looking at some random file it looked like delays happen when there's colors.  I
disabled font-lock-mode and that made it usable again.

**Comment by KLuka** [comment]
_From [riccardi...@gmail.com](https://code.google.com/u/110092272103816952673/) on October 03, 2010 05:15:22_

I also retried with svn r239 : it's still slow. And exactly like elibarzi, when disabling colors it is usable again on some files, but not all:

I opened a large html file, and the issue is still there.

When resizing the webbrowser window, the loading time changes: when the window is small (80x46), it's fast (probably loaded in one time), and when the window is large (163x46), it's slow (it seems to be loaded per small blocs, with a delay of about 1 sec between each bloc).

The color decreases the window size at which the loading is not instantaneous.

So it seems to be a maximum size of data sent, colored text being larger than just b&w text.


I tried to increase #define MAX_RESPONSE, but it changed nothing (loading cut in blocs in the same way).


With wireshark we can see that one ssh packet is sent every exactly 1 sec, with a length of 224 bytes, when loading a slow file in emacs.

So the issue is not between shellinabox and the webbrowser, but definitely between the ssh daemon and shellinabox.

**Comment by KLuka** [comment]
_From [elibarzi](https://code.google.com/u/elibarzi/) on October 03, 2010 19:34:07_

FWIW, I was using the LOGIN service, without SSL.

**Comment by KLuka** [comment]
_From [Otto.Lin...@googlemail.com](https://code.google.com/u/107433514798780608923/) on June 20, 2012 12:45:29_

This bug is still not fixed. Does anybody looking for it?

**Comment by KLuka** [comment]
_From [M.A....@gmx.de](https://code.google.com/u/108597750725611823604/) on February 19, 2013 03:05:50_

try playing with 'stty speed'

e.g.
$ stty speed 38400

@zodiac:
Maybe a default Terminal speed would be good, even if it only fixes some emacs issue...

**Comment by nocnokneo** [comment]
With `stty speed 38400` I see a big improvement! If this is the best solution we can come up with for the problem, then I agree that it would be nice if shellinabox could set this automatically.

**Comment by KLuka** [comment]
@nocnokneo Hi, I will check this out ...

Could this fix be related to some comments in issue #58 (see 9th comment)?

As I can understand original author has some problems with this fix, because it doesn't fit into POSIX standard... Maybe we could apply some conditional compilation for this?

**Comment by KLuka** [comment]
@nocnokneo Ok, i think i made the correct patch. 

I tested this on Ubuntu 12.04 and it works fine for me. It correctly sets default tty speed to 38400 and fits to POSIX standard :) In previous patch the speed was probably overwritten with other data in `tt` struct.

Can you also test this patch and report back?

```diff
--- a/shellinabox/launcher.c
+++ b/shellinabox/launcher.c
@@ -1509,13 +1509,13 @@ static void childProcess(struct Service *service, int width, int height,
   // Set initial terminal settings
   struct termios tt = { 0 };
   tcgetattr(0, &tt);
-  cfsetispeed(&tt, 38400);
-  cfsetospeed(&tt, 38400);
   tt.c_iflag                    =  TTYDEF_IFLAG & ~ISTRIP;
   tt.c_oflag                    =  TTYDEF_OFLAG;
   tt.c_lflag                    =  TTYDEF_LFLAG;
   tt.c_cflag                    = (TTYDEF_CFLAG & ~(CS7|PARENB|HUPCL)) | CS8;
   tt.c_cc[VERASE]               = '\x7F';
+  cfsetispeed(&tt, B38400);
+  cfsetospeed(&tt, B38400);
   tcsetattr(0, TCSAFLUSH, &tt);

   // Assert root privileges in order to update utmp entry.
```

**Comment by mmosharov** [comment]
looks like this issue is reproduced for me :(
OS: Ubuntu 14.04.4,
browser: Chrome 50.0.2661.94 m
shellinabox: version 2.10 (revision 239)
steps are the same as in first comment
and if i type "stty speed 38400", problem disappear
thanks!

**Comment by KLuka** [comment]
Hi, @mmosharov. This issue is resolved... Please use the latest version of shellinabox - 2.19.

**Comment by mmosharov** [comment]
Hi @KLuka. I thought that typing "sudo apt-get install shellinabox" will get me the latest version, but looks like it does not
i will try, thanks a lot!
