### ISSUE TITLE
a service not in PATH fails to execute

### ISSUE THREAD

**Issue by KLuka** [shellinabox/shellinabox#53]
_From [happily....@gmail.com](https://code.google.com/u/105414482566354419735/) on February 19, 2010 00:19:16_

What steps will reproduce the problem? 1. Run shellinaboxd with a service argument that points at a binary not in 
$PATH (as seen from shellinaboxd). E.g.: -s 
/:shellinabox:shellinabox:/:/usr/local/scripts/sb-ssh-wrapper ${url}
2. Connect to the running shellinaboxd instance from a browser to initiate 
a new session. What is the expected output? What do you see instead? Expected: The session starts successfully and the browser displays the 
output of the above script.

What happens: shellinaboxd strips the path information from the service 
definition and uses execvp() to find the service in $PATH. Since 
/usr/local/scripts is not in $PATH, it fails to find sb-ssh-wrapper and 
fails. All I get is "Session closed" in the web browser.

This behavior is at the very end of the execService() function in 
shellinabox/launcher.c. I confirmed it by strace'ing shellinaboxd:

[pid  7029] chdir("/")                  = 0
[pid  7029] execve("/usr/local/bin/sb-ssh-wrapper", 
["/usr/local/scripts/sb-ssh-wrappe"..., " https://realify.com/ssh/gary/" ], 
[/* 8 vars */]) = -1 ENOENT (No such file or directory)
[pid  7029] execve("/usr/bin/sb-ssh-wrapper", ["/usr/local/scripts/sb-ssh-
wrappe"..., " https://realify.com/ssh/gary/" ], [/* 8 vars */]) = -1 ENOENT 
(No such file or directory)
[pid  7029] execve("/bin/sb-ssh-wrapper", ["/usr/local/scripts/sb-ssh-
wrappe"..., " https://realify.com/ssh/gary/" ], [/* 8 vars */]) = -1 ENOENT 
(No such file or directory)
[pid  7029] execve("/usr/games/sb-ssh-wrapper", ["/usr/local/scripts/sb-
ssh-wrappe"..., " https://realify.com/ssh/gary/" ], [/* 8 vars */]) = -1 
ENOENT (No such file or directory)
[pid  7029] exit_group(1)               = ?

execService() needs to not strip path information from the first argument 
to execvp().

Moving sb-ssh-wrapper to /usr/local/bin (which is in $PATH) made the 
problem go away. What version of the product are you using? On what operating system? Version: 2.10-1
OS: Debian Lenny (5.0.4)
shellinabox is compiled from source using the Debian package definition in 
the source tarball.

_Original issue: http://code.google.com/p/shellinabox/issues/detail?id=53_

**Comment by KLuka** [comment]
_From [d250labo...@gmail.com](https://code.google.com/u/111142454391051438789/) on February 27, 2012 17:20:55_

I can confirm the same behaviour on CentOs 6.2.

**Comment by KLuka** [comment]
_From [jer...@nickurak.ca](https://code.google.com/u/102019683200554479931/) on October 02, 2013 22:00:05_

Very confusing, never would have realised this was my problem if this bug wasn't filed, thanks :)

**Comment by tickelton** [comment]
This should have been fixed by 0fcf50735efcd903e29984182f267e745a7bb2f6.
Since then the path of the command to execute isn't stripped for the actual file any longer but only for the argv[0] parameter to execve.

    char *cmd                   = strdup(argv[0]);
    char *slash                 = strrchr(argv[0], '/');
    if (slash) {
      memmove(argv[0], slash + 1, strlen(slash));
    }   
    if (service->useDefaultShell) {
      int len                   = strlen(argv[0]);
      check(argv[0]             = realloc(argv[0], len + 2));
      memmove(argv[0] + 1, argv[0], len);
      argv[0][0]                = '-';
      argv[0][len + 1]          = '\000';
    }   
    execvp(cmd, argv);

Can anybody still reproduce this with the current version ?

**Comment by KLuka** [comment]
I also can't reproduce this problem. Issue is solved :+1:
