### ISSUE TITLE
Shellinabox does not work on an ipad

### ISSUE THREAD

**Issue by KLuka** [shellinabox/shellinabox#64]
_From [dlangh@gmail.com](https://code.google.com/u/dlangh@gmail.com/) on April 20, 2010 20:58:03_

What steps will reproduce the problem? 1. Goto shellinabox site.  You can login, but each time enter is pressed, the screen is cleared. What is the expected output? What do you see instead? No clearing of the screen when enter is pressed. What version of the product are you using? On what operating system? I tried multiple in vain.  From 2.3 to 2.10 Please provide any additional information below. I recognize this is probably not going to be a high priority right now, but the fix has got to be 
something simple I would hope.  It works in normal Safari in Mac OSX.  This would be an 
awesome way to manage servers with an ipad if it could work!

_Original issue: http://code.google.com/p/shellinabox/issues/detail?id=64_

**Comment by KLuka** [comment]
_From [dlangh@gmail.com](https://code.google.com/u/dlangh@gmail.com/) on April 20, 2010 12:01:30_

just a quick update.  Oddly enough it works in the ipad simulator (available as part of xcode SDK 3.2).  So I'm not 
sure why it's failing on a physical ipad.

**Comment by KLuka** [comment]
_From [Knightw...@gmail.com](https://code.google.com/u/112413176119934100133/) on August 01, 2010 23:14:09_

I have tried this on my Ipad, it unfortunately does not work :(. It would be awesome to get this bug fixed. It would open up my Linux Server to some cross-platform use and give all of those people with an Ipad the chance to enjoy open source software on the command line from their browser.

**Comment by KLuka** [comment]
_From [zod...@gmail.com](https://code.google.com/u/109388341641331418132/) on August 01, 2010 23:38:54_

I am sure it isn't going to require any big changes, as iPad is just supposed to be WebKit. But for lack of an iPad, there isn't much I can do to test anything. I'd happily accept patches though...

**Comment by KLuka** [comment]
_From [Knightw...@gmail.com](https://code.google.com/u/112413176119934100133/) on August 01, 2010 23:42:12_

If you want me to help you test it, i'll be more then happy to help. Just point me (and my ipad) towards a server running the "bleeding edge" version of Shellinabox and i'll do some tests if you want to.

**Comment by KLuka** [comment]
_From [zod...@gmail.com](https://code.google.com/u/109388341641331418132/) on August 02, 2010 08:27:55_

The project's home page always runs the most recent version of the Javascript code. In fact, it runs the code directly from the subversion repository.

**Comment by KLuka** [comment]
_From [frip%arc...@gtempaccount.com](https://code.google.com/u/115490539554892113853/) on August 02, 2010 10:08:53_

I found out that on iPad this.isEmbedded isn't set correctly. It seems that the Mobile Safari doesn't support some attributes for the screen. So this.isEmbedded is set to true, when it shouldn't be.
A quick hack:
In vt100.js add the following code lines after the first occurence of this.isEmbedded
 
var isMobile = navigator.userAgent.match(/iPad|iPhone|iPod/i) != null;
if (isMobile) {
        this.isEmbedded = false;
}

It's only a quick hack;-)
It's sad that the iPad keyboard doesn't have a tab key.

**Comment by KLuka** [comment]
_From [Knightw...@gmail.com](https://code.google.com/u/112413176119934100133/) on August 02, 2010 22:55:59_

I've tested it on the projects page and was able to enter some "basic" commands (no pun intended). It does however take a few 'taps' in the window to trigger the ipad keyboard to pop up. I've also tried it on my own install of Shellinabox. I managed to log in , but then i get some strange screen. (i'll try to make a screenshot of that too later). Included is a screenshot of the default ipad keyboard. If you guyz need anything else let me know.

**Attachment:** [photo.PNG](http://code.google.com/p/shellinabox/issues/detail?id=64#hc7)

**Comment by KLuka** [comment]
_From [zod...@gmail.com](https://code.google.com/u/109388341641331418132/) on September 04, 2010 10:55:26_

I added an option on-screen keyboard. Let me know, if this improves things for iPad users.

**Comment by KLuka** [comment]
_From [robert.m...@gmail.com](https://code.google.com/u/106986416106287498333/) on December 01, 2010 01:26:31_

The fix in comment 6 has solved this for me on svn trunk@239. Would be nice to see this is the code base normal.

**Comment by KLuka** [comment]
_From [rebound1...@gmail.com](https://code.google.com/u/103512134821022628905/) on December 11, 2010 14:27:55_

Hi fix in comment 6 resolve this for me; however, the ESC key is not coming through when using vi. The arrow keys is also not usable (for command history). Is there any minor change to fix those issues as well? 

On side note, I installed the latest svn version, but couldn't see how to activate the on-screen keyboard. Has the on-screen keyboard been implemented already? 

Many thanks

**Comment by KLuka** [comment]
_From [zod...@gmail.com](https://code.google.com/u/109388341641331418132/) on December 11, 2010 14:31:32_

If you enable the on-screen keyboard from the context menu, you should now see a little icon in the top right-hand corner that opens the keyboard. You can try this from the project's homepage at http://shellinabox.com

**Comment by KLuka** [comment]
_From [mindboos...@gmail.com](https://code.google.com/u/103664875831021260164/) on June 08, 2012 07:52:42_

Is there any way to make the on-screen keyboard option being active by default?
Selecting it in a touchscreen-only device might be tricky, since it won't be easy do do a "right click" to go to the menu...

**Comment by a-detiste** [comment]
@KLuka this one has been fixed for a long time
